aws-controllers-k8s/code-generator

pkg/generate/ack/controller.go
templates/pkg/version/version.go.tpl

Issue: N/A
Changes:
- Add `pkg/version/version.go.tpl` template
- Add version template to Go template set

Generate `pkg/version/version.go` file

---

.github/workflows/unit-tests.yaml

Issue: N/A
Changes:
- Add github action configuration file to run unit tests on pull requests

Add github actions to run unit tests

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

Issue N/A
- Add github Issues and PullRequests templates

Add github Issues and PullRequests templates

---

templates/crossplane/pkg/controller.go.tpl

Description of changes: `Secret` resource from `SecretsManager` has special logic around deletion and we need to work on the response of the deletion call, hence `postDelete` hook.

crossplane: add postDelete hook

---

templates/pkg/resource/sdk_update.go.tpl

Caused SageMaker ModelMonitor Test to fail. 
Bug Fix in post_build_request Hook

Bug Fix: typo in post_build_request Hook

---

pkg/generate/code/set_resource.go

Part of Issue: https://github.com/aws-controllers-k8s/community/issues/773 
- panic if an input field rename is not part of a resource spec/status fields
- Change `code.setResourceReadMany` to concider renames when checking "matchFieldName" configuration

Panic if input field renames are not part of a resource spec/status fields

---

pkg/generate/ack/hook.go
templates/pkg/resource/delta.go.tpl

Issue https://github.com/aws-controllers-k8s/community/issues/796
- Add pre/post compare hooks for `newResourceDelta` function

Add pre/post compare hooks for `newResourceDelta` function

---

templates/pkg/resource/sdk.go.tpl

Issue N/A
- Adds missing `sdk_delete_post_build_request` hook in `sdk.go.tpl`

Add missing `sdk_delete_post_build_request` hook in `sdk.go.tpl`

---

pkg/generate/ack/release.go

Add metrics-service.yaml to helm template files.

Add metrics-service.yaml to helm template files.

---

pkg/names/names.go

Adds the CORS (Cross-Origin Resource Sharing) initialism to the list.

Add CORS to initialisms

---

templates/pkg/resource/resource.go.tpl

Description of changes: Generate the new `SetStatus` method, for patching the status of a resource from an another.

Add `SetStatus` for resource

---

Makefile
go.mod
go.sum

Update the dependent version of ACK runtime to `v0.12.0` and update the `ackgenerate` version

Update to ACK runtime `v0.12.0`

---

pkg/names/names.go
pkg/names/names_test.go

* Update `ami` entry to prevent replacement in "Family"
Testing:
* `make test` ✅ 

update ami rule in initialisms

---

templates/pkg/resource/manager.go.tpl

Addresses https://github.com/aws-controllers-k8s/code-generator/pull/182#discussion_r704233419
Testing:
mode e2e test using sagemaker controller

compare ptr using ==

---

Makefile
go.mod
go.sum

Upgrade to ACK runtime `v0.14.0`

Update to ACK runtime `v0.14.0`

---

OWNERS
OWNERS_ALIASES

Add Bryan Carter to OWNERS

---

pkg/names/names.go
pkg/names/names_test.go

* Adds `NAT` to initialism with preventions

add NAT to initialisms

---

pkg/model/model.go

When implementing the update code paths for OpenSearchService, I found
out I needed to ignore the AutoTuneOptions.RollbackOnDisable nested
field within the UpdateDomainConfigInput shape. When I went to put the
following in the `generator.yaml` file:
```yaml
ignore:
field_paths:
- UpdateDomainConfigInput.AutoTuneOptions.RollbackOnDisable
```
What ended up happening is that the *entire* AutoTuneOptions field was
ignored instead of just the RollbackOnDisable field.
This patch fixes this situation by modifying the
`pkg/model.Model:ApplyIgnoreShapeRules()` method to account for nested
field paths and not just a two-level field path that has the Input or
Output shape name as the first part of the field path and the top-level
member field name as the second part of the field path.
Signed-off-by: …

allow ignore nested fieldpaths

---

templates/helm/templates/NOTES.txt.tpl

Noticed a couple small mistakes in the NOTES.txt template for Helm; this
commit addresses both.

small fixes to NOTES.txt template for Helm

---

pkg/generate/ack/controller.go
templates/cmd/controller/main.go.tpl

* Add cross controller referenced resources to scheme
* Tested locally with successful reconciliation of referencing Subnet resource from ec2-controller inside VPCLink resource of apigatewayv2-controller

Add cross controller referenced resources to scheme

---

go.mod
go.sum

Update runtime to `v0.18.4`

---

templates/helm/templates/deployment.yaml

fix trailing whitespace in Helm deployment template

---

go.mod
go.sum
pkg/generate/code/set_resource_test.go

Upgrade `aws-controllers-k8s/pkg`

Upgrade `aws-controllers-k8s/pkg` version

---

go.mod
go.sum
pkg/generate/code/set_resource_test.go

Pin `ack/pkg` to `v0.0.1`

---

pkg/config/config.go
pkg/config/field.go
pkg/fieldpath/path.go
pkg/generate/code/check.go
pkg/generate/code/compare.go
pkg/generate/code/initialize_field.go
pkg/generate/code/late_initialize.go
pkg/generate/code/resource_reference.go
pkg/generate/code/set_resource.go
pkg/generate/code/set_sdk.go
pkg/generate/code/synced.go
pkg/model/multiversion/delta.go
pkg/model/multiversion/delta_renames.go
pkg/model/types.go

gofmt 1.20 updates (style-only changes)

---

templates/pkg/resource/sdk_update_set_attributes.go.tpl

The sdkUpdate method template for attribute-based APIs was missing the custom hook point injections. This patch adds them in. This is necessary for support of tags in SQS controller.
Issue aws-controller-k8s/community#1541

Inject missing code hook points in set attributes

---

templates/helm/templates/deployment.yaml
templates/helm/values.schema.json
templates/helm/values.yaml.tpl

Discussed in https://github.com/aws-controllers-k8s/community/pull/1890#discussion_r1319080739 
Add `deployment.replicas` helm value

Add `deployment.replicas` helm value

---

go.mod
go.sum

Upgrade the pkg library for the code generator from 0.0.6 to 0.0.7

Upgrade pkg library to 0.0.7

---

scripts/lib/common.sh

Bump controller-gen minimum version to v0.14.0

---

go.mod
go.sum

Pin `github.com/aws-controllers-k8s/pkg` to v0.0.9

---

Dockerfile.local

[local builds] move instructions to copy code before go mod commands

---

Dockerfile.local

[runtime builds] Include mocks and run `go mod tidy` before builds

---

go.mod
go.sum

Pin ACK pkg to `v0.0.12`

---

go.mod
go.sum

Pin ACK runtime to `v0.33.0`

---

go.mod
go.sum

Pin ACK PKG to v0.0.13

---

go.mod
go.sum

Pin ACK PKG to v0.0.14

---

pkg/model/crd.go

Say we want to overwrite a nested field type e.g. for `WAFv2` controller (this is needed due to a cyclic dependency):
```
resources:
RuleGroup:
Rules.Statement.AndStatement:
type: string
```
Currently, the [overwrite code logic](https://github.com/aws-controllers-k8s/code-generator/blob/62466746500d0c01fcfa8e8e3ca6abd9386e4687/pkg/model/crd.go#L660-L687) does not work for the above scenario and it returns the following error:
```
Expected parent field to be of type structure, but found list
```
This happens because `Rules` is not of type `struct`, but `[]struct`, and the referenced code logic requires that all fields within the path (i.e. `Rules` and `Statement` to be of type `struct`).
This PR relaxes the logic to allow fields within the …

Support custom nested fields that have path that contains types other than struct

---

go.mod
go.sum
pkg/generate/code/set_resource_test.go
pkg/generate/code/set_sdk_test.go

Pin ACK PKG to v0.0.15

---

go.mod
go.sum

Pin runtime to v0.38.0

---

templates/config/controller/deployment.yaml.tpl

This change will allow us to include environment variable
for feature gates, specifically when testing specific ones

Add `FEATURE_GATES` env to controller deployment template

---

templates/helm/values.yaml.tpl

Expose `ResourceAdoption` feature gate in helm chart values

---

go.mod
go.sum

Pin ACK runtime to v0.42.0

---

go.mod
go.sum

Pin ACK runtime to v0.45.0

---

go.mod
go.sum

- Update pkg dependency to v0.0.17

Update pkg to v0.0.17

---

go.mod
go.sum

Pin ACK runtime to v0.46.1

---

pkg/generate/ack/release.go

Fixed the generation of reconcile resources in the Helm chart to use proper CamelCase Kind names. The previous implementation using `metaVars.CRDNames` with `names.New(name).Camel` was incorrectly converting CRD names from their lowercase plural form, resulting in improper capitalization.
The previous approach used `metaVars.CRDNames` which contains lowercase plural forms (e.g., "preparedstatements", "workgroups"). When these were processed through `names.New(name).Camel`, it only capitalized the first letter without properly handling internal word breaks, leading to incorrect resource kind names.
Issue:
```yaml
resources:
- Preparedstatements    # incorrect
- Workgroups           # incorrect
```
Fix:
```yaml
resources:
- PreparedStatement  
- WorkGroup
```
By …

fix: Use correct CamelCase Kind names in reconcile resources

---

.gitignore

- Add .vscode folder to .gitignore

Ignore .vscode files

---

go.mod
go.sum

Update pkg to 0.0.18

---

templates/helm/templates/deployment.yaml.tpl
templates/helm/values.yaml.tpl

Add the ability to set the deployment's update strategy via chart values.

add deployment.strategy to chart

---

go.mod
go.sum

Pin ACK runtime to v0.49.0

---

go.mod
go.sum

Pin ACK runtime to v0.51.0
