- cmd/ack-generate/command/apis.go
- templates/cmd/controller/main.go.tpl
- templates/pkg/resource/descriptor.go.tpl
- templates/pkg/resource/manager_factory.go.tpl
- templates/pkg/resource/resource.go.tpl
- templates/pkg/resource/sdk.go.tpl
Updates the import paths in templates that refer to the service
controller's separate repository package paths.
Also updates the `ack-generate apis` command to respect a supplied
`--output` path argument and not automatically append the service alias
to the supplied output path.
Issue aws/aws-controllers-k8s#666
> update template service controller pkg paths

- Makefile
- scripts/build-controller.sh
Follow up to #6 
- Add `-tags codegen` to `go get` ack-generate binary help message
- Add `TEMPLATES_DIR` to the USAGE help message
- Remove `build-ack-generate` from the prerequired rules of `build-controller`
> Enhance `scripts/build-controller.sh` USAGE and error messages

- cmd/ack-generate/command/apis.go
- cmd/ack-generate/command/common.go
- cmd/ack-generate/command/controller.go
- cmd/ack-generate/command/root.go
- scripts/build-controller.sh
Issue N/A
- Use one shared optOutputPath for both API and Controller sub commands 
- Add a CLI flag to set the version of aws-sdk-go used by `ack-generate`
> Add a CLI flag to set the version of aws-sdk-go used by `ack-generate`

- scripts/build-controller.sh
Running `make build-controller SERVICE=$SERVICE` fails with error:
```
./scripts/build-controller.sh: line 63: ack-generate: command not found
make: *** [build-controller] Error 127
```
The issue was because of `ack-generate` inside usage text. This pull request updates it to 'ack-generate' to fix the issue.
> fix for ack-generate: command not found

- templates/apis/crd.go.tpl
- templates/cmd/controller/main.go.tpl
- templates/pkg/resource/descriptor.go.tpl
- templates/pkg/resource/identifiers.go.tpl
- templates/pkg/resource/manager.go.tpl
- templates/pkg/resource/manager_factory.go.tpl
- templates/pkg/resource/registry.go.tpl
- templates/pkg/resource/resource.go.tpl
- templates/pkg/resource/sdk.go.tpl
1. Need to update go files import paths to new repo path:
`make build-controller SERVICE=$SERVICE` generates service controller go code files that refer to old repo paths:
* `github.com/aws/aws-controllers-k8s/pkg`
* `github.com/aws/aws-controllers-k8s/apis`
This lead to failure in compilation when `make test` is executed from service controller repo.
2. `main.go.tpl` needs to supply additional VersionInfo to `ackrt.NewServiceController()` method.
Updated templates files for service controller go code to import paths for new split repos:
* `github.com/aws-controllers-k8s/runtime/pkg`
* `github.com/aws-controllers-k8s/runtime/apis`
After making these changes, tested the changes using:
```
cd …
```
> Update go templates to use runtime/pkg and runtime/apis as per split repo

- scripts/lib/aws.sh
Currently, the kind-test uses the `daws` script to run AWS cli commands. However, it does not respect $AWS_PROFILE, and instead always uses default.
This pull request changes it, such that if $AWS_PROFILE is set, it will be passed as an environment variable to the Docker run.
There is a tiny bit of wonkiness so that it does not pass anything when $AWS_PROFILE is not set - because in testing, I could not get the --profile option (which may never be used in this setting, either way) to override the environment variable even if it's set to empty.
> Add support for non-default AWS profile

- templates/crossplane/pkg/controller.go.tpl
Description of changes: Changes the error wrapping method in Crossplane controller template.
> crossplane: update controller template to use aws-specific error wrapper

- cmd/ack-generate/command/release.go
When running `./test/release/test-helm.sh` from the community
repository, I was getting errors like this:
```
[jaypipes@thelio community]$ ./test/release/test-helm.sh s3 v0.0.2-37-g6c6957d-dirty
testing Helm release for s3 for release version v0.0.2-37-g6c6957d-dirty.
Building release artifacts for s3-v0.0.2-37-g6c6957d-dirty
Error: open apis: no such file or directory
```
The above was due to the `ack-generate release` command calling the
`getLatestAPIVersion()` function which in turn attempted to read the
(old, pre-split-repo) `services/$SERVICE/apis/` directory. We don't
actually need the latest API version when generating release artifacts
for a controller, but the `pkg/generate.New()` function requires an
APIVersion argument, so I'm just passing an empty string here, which
solves the …
> fix ack-generate release

- templates/pkg/resource/sdk.go.tpl
- templates/pkg/resource/sdk_find_read_one.go.tpl
- sdkFind readOne: Allows adding/setting custom output. Similar to [sdkFind readMany](https://github.com/aws-controllers-k8s/code-generator/blob/main/templates/pkg/resource/sdk_find_read_many.go.tpl#L25-L31)
- sdkDelete: Introduce adding custom implementation for delete operation
Using SageMaker Controller
TBD - link related PRs
> add custom methods for sdkFind readOne and sdkDelete

- templates/crossplane/pkg/controller.go.tpl
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/697
Description of changes: Apparently, I forgot to use the `nopFilterList` function as default, which in turn causes https://github.com/aws-controllers-k8s/community/issues/697 to happen.
Fixes https://github.com/aws-controllers-k8s/community/issues/697
> crossplane: use nopFilterList as default filterList implementation

- templates/crossplane/pkg/controller.go.tpl
Description of changes: There are cases like `Lambda Function` where there are both ReadMany and ReadOne operations available. The first choice is always ReadOne, so we need to take that into account here as well.
> crossplane: fix controller template for resources that might have both ReadOne and ReadMany

- pkg/generate/code/set_sdk.go
- pkg/generate/code/set_sdk_test.go
- pkg/generate/config/field.go
- pkg/generate/elasticache_test.go
- pkg/generate/testdata/models/apis/elasticache/0000-00-00/generator.yaml
- pkg/model/field.go
- templates/pkg/resource/sdk.go.tpl
- templates/pkg/resource/sdk_update.go.tpl
- Introduced a new field config for secrets.
- This will turn a given field into SecretKeyRef.
- Initial approach to solve ElastiCache
AuthToken usecase.
Other PR -
Runtime changes -
ElastiCache generated code - 
> SecretKeyRef - CodeGen changes

- cmd/ack-generate/command/apis.go
- cmd/ack-generate/command/controller.go
- cmd/ack-generate/command/crossplane.go
- cmd/ack-generate/command/olm.go
- cmd/ack-generate/command/release.go
- cmd/ack-generate/command/root.go
- pkg/generate/ack/apis.go
- pkg/generate/ack/controller.go
- pkg/generate/ack/release.go
- pkg/generate/crossplane/crossplane.go
- pkg/generate/olm/olm.go
- pkg/generate/templateset/templateset.go
- scripts/build-controller.sh
We want different teams to have the ability to specify template
overrides for their specific controller or generated codebase.
There are a number of use cases where having the ability to specify
multiple "template search paths" will be useful.
Imagine that the ElastiCache ACK controller team wants to change their
boilerplate.txt content to mention something specific to ElastiCache.
Instead of adding a bunch of conditional statements to the code
generator or new fields to the generator configuration object (which is
already complicated), what if the maintainer team could add their custom
boilerplate text to a `templates/boilerplate.txt` file in the
elasticache-controller source repository and call `ack-generate`
commands like this:
```bash …
```
> add multiple template base path functionality

- pkg/generate/ack/controller.go
- pkg/generate/code/compare.go
- pkg/generate/code/compare_test.go
- pkg/generate/config/field.go
- pkg/generate/testdata/models/apis/s3/0000-00-00/generator.yaml
- templates/pkg/resource/delta.go.tpl
- templates/pkg/resource/descriptor.go.tpl
- templates/pkg/resource/manager.go.tpl
- templates/pkg/resource/resource.go.tpl
- templates/pkg/resource/sdk_update.go.tpl
- templates/pkg/resource/sdk_update_custom.go.tpl
- templates/pkg/resource/sdk_update_not_implemented.go.tpl
- templates/pkg/resource/sdk_update_set_attributes.go.tpl
adds code generation for field comparisons
Adds new code generation functions to `pkg/generate/code` that output Go
code that compares fields of various types and calls `delta.Add()` if a
difference is detected.
For fields with underlying scalar types, the generated code looks like
this:
```go
if *a.ko.Spec.Name != *b.ko.Spec.Name) {
delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
}
```
For non-scalar types, generated code recurses over the fields and/or
calls specialized comparison functions in the runtime library's
`pkg/compare` module. Here is an example of a complex underlying field
type and what the generated code might look like:
```go
if ackcompare.HasNilDifference(a.ko.Spec.CreateBucketConfiguration, b.ko.Spec.CreateBucketConfiguration) { …
```
> adds code generation for field comparisons

- scripts/build-controller.sh
Followup to: #8 
- Use `AWS_SDK_GO_VERSION` to set the cache version used to generate APIs/CRDs
> Use AWS_SDK_GO_VERSION to set the cache version used to generate APIs/CRDs

- pkg/generate/code/compare.go
Issue N/A
Changes:
- Fix resourec delta code generation when `nilCode` is empty
- Return an empty string for non implemented cases
Description:
When generating sagemaker controller using `make build-controller SERVICE=sagemaker` we can observe the following error:
```
Building Kubernetes API objects for sagemaker
Generating deepcopy code for sagemaker
Generating custom resource definitions for sagemaker
Building service controller for sagemaker
Error: template: /home/amine/source/github.com/aws-controllers-k8s/code-generator/templates/pkg/resource/delta.go.tpl:21:3: executing "/home/amine/source/github.com/aws-controllers-k8s/code-generator/templates/pkg/resource/delta.go.tpl" at <GoCodeCompare .CRD "delta" "a.ko" "b.ko" 1>: error calling GoCodeCompare: strings: negative Repeat count …
```
> Fix resource delta code generation

- go.mod
- go.sum
- pkg/generate/ack/runtime_test.go
`code-generator` refers to `v0.0.4` version of `runtime`.
The `code-generator` templates use new `Delta` functionality.
But as the `Delta` functionality corresponds to `v0.0.5` version of `runtime`; `code-generator` needs to refer to `v0.0.5` version of runtime.
* Updated `go.mod` file to refer `v0.0.5` version of `runtime`
* Updated unit test to check resource descriptor methods.
> refer runtime v0.0.5 with Delta() support

- templates/apis/crd.go.tpl
Uses the aws-sdk-go private/model/api.Shape.Documentation functionality
to write out docstrings for individual fields used in a CRD. Crossplane
was already doing this; ACK CRDs are now caught up.
Issue aws-controllers-k8s/community#723
Tested locally with S3 controller and works like a charm.
> add docstrings to CRD fields

- pkg/generate/code/compare.go
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/729
Description of changes: Refactor `MapStringStringEqual` references to `MapStringStringPEqual`, so that it compares the string pointers rather than expecting pure strings.
> Refactor MapStringStringEqual to MapStringStringPEqual

- pkg/generate/code/set_resource.go
- pkg/generate/code/set_resource_test.go
- pkg/generate/generator.go
- pkg/generate/testdata/models/apis/rds/0000-00-00/generator.yaml
- pkg/model/field.go
- pkg/names/names.go
If fields were renamed in some operations, the code generated for
`SetResource()` was not properly looking up the renamed field. This
patch updates `SetResource()` to first check if the field has 
renamed for the referred Operation and if so, look up the CRDField
object in the CRD.SpecFields collection instead of the StatusFields
collection.
> handle renamed fields in SetResource generation

- pkg/generate/code/set_resource.go
- pkg/generate/code/set_resource_test.go
Currently, we create a [copy for the current resource state](https://github.com/aws-controllers-k8s/code-generator/blob/main/templates/pkg/resource/sdk_find_read_one.go.tpl#L29) in sdkFind and merge the output of describe output if it is non-nil. This doesn't work for fields that can toggle between nil and non-nil. The latest resource should match the output from AWS service. This PR addresses this issue
with sagemaker controller [aws-controllers-k8s/sagemaker-controller#7](https://github.com/aws-controllers-k8s/sagemaker-controller/pull/7)
Change is not implemented for the `ko.Status.ACKResourceMetadata` field because the only case I see where it can toggle is if the user changes the name of resource they created, in which case `sdkFind` will throw an `ackerr.NotFound` error and …
> Handle nil fields in response from describe API output - readOne and readMany

- pkg/generate/codedeploy_test.go
- pkg/generate/generator.go
- pkg/generate/testdata/models/apis/codedeploy/0000-00-00/generator.yaml
- pkg/model/crd.go
- pkg/model/printer_column.go
When returning AdditionalPrinterColumns for a CRD, we now always sort
the list of PrinterColumn structs by their Name. This prevents the
non-deterministic behaviour we've seen in Issue #720.
Also, the `pkg/generate:Generator.GetCRDs()` method was incorrectly only
adding PrinterColumns to a CRD when the field was specified as being
sourced from a different shape than the Create input or output shape (in
other words, only when the `pkg/generate/config.FieldConfig.From` field
was non-nil). This patch corrects this so that any field in a resource
may be marked as a printer column.
Fixes Issue aws-controller-k8s/community#720
> always sort additional printer columns

- templates/helm/Chart.yaml.tpl
Issue #, if available: None
Description of changes: The helm `Chart.yaml` files still referenced the older repository structure. 
I also added a reference to the maintainer of the service controller team.
> Update Chart.yaml for split repositories

- templates/pkg/resource/sdk.go.tpl
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/498
Description of changes: RecoverableCondition is used to report errors that are not marked as Terminal. Currently controllers sync silently and errors are not reported. Reporting will notify Recoverable errors that can likely be fixed without re-applying the spec. 
Testing: Ran reconciler unit tests
go test -v
=== RUN   TestReconcilerUpdate
2021-04-05T18:51:38.576Z	INFO	ackrt	updated resource	{"kind": "Book", "namespace": "default", "name": "mybook", "generation": 1, "is_adopted": false}
--- PASS: TestReconcilerUpdate (0.00s)
=== RUN   TestRegistry
--- PASS: TestRegistry (0.00s)
=== RUN   TestServiceController
--- PASS: TestServiceController (0.00s)
=== RUN   TestIsAdopted
--- PASS: TestIsAdopted (0.00s)
=== …
> Adding status reporting for RecoverableCondition

- templates/helm/Chart.yaml.tpl
The Chart.yaml.tpl was missing a space after the `url:` element for
maintainer team, resulting in the following error when eventually
running the scripts/helm-publish-chart.sh script:
```
Generating Helm chart package for mq@v0.0.2 ... Error: cannot load Chart.yaml: error converting YAML to JSON: yaml: line 15: could not find expected ':'
```
> fix up missing space in url element of helm chart

- pkg/generate/ack/controller.go
- pkg/generate/ack/hook.go
- pkg/generate/ack/hook_test.go
- pkg/generate/ack/testdata/templates/sdk_delete_pre_build_request.go.tpl
- pkg/generate/config/resource.go
- pkg/generate/templateset/templateset.go
- pkg/generate/testdata/models/apis/mq/0000-00-00/api-2.json
- pkg/generate/testdata/models/apis/mq/0000-00-00/docs-2.json
- pkg/generate/testdata/models/apis/mq/0000-00-00/generator.yaml
- pkg/util/file.go
- templates/pkg/resource/sdk.go.tpl
- templates/pkg/resource/sdk_find_get_attributes.go.tpl
- templates/pkg/resource/sdk_find_read_many.go.tpl
- templates/pkg/resource/sdk_find_read_one.go.tpl
- templates/pkg/resource/sdk_update.go.tpl
This patch adds support for a generic callback system into the generator
config that allows controller implementors to specify some code that
should be injected at specific named points in a template. I expect that
eventually this generic hook system will be more useful, flexible and
extensible than the hodge-podge of custom callback methods and overrides
currently in the generator config.
The `pkg/generate/config.ResourceConfig` struct now has a `Hooks` field
of type `map[string]*HookConfig`, with the map keys being named hook
points, e.g. "sdk_update_pre_build_request".
There are two ways to inject code at hook points: inline and via a
template path. The inline method uses the `HookConfig.Code` field which
should contain the Go code that gets injected at a named hook point. The …
> add support for generic callback hooks

- pkg/generate/ack/hook.go
- templates/pkg/resource/sdk.go.tpl
- templates/pkg/resource/sdk_find_get_attributes.go.tpl
- templates/pkg/resource/sdk_find_read_many.go.tpl
- templates/pkg/resource/sdk_find_read_one.go.tpl
- templates/pkg/resource/sdk_update.go.tpl
Adds a hook for post_set_output
Locally using sagemaker controller
```
TrainingJob:
...
hooks:
sdk_delete_pre_build_request:
template_path: training_job/sdk_delete_pre_build_request.go.tpl
sdk_create_post_set_output:
template_path: training_job/sdk_create_post_set_output.go.tpl
```
> hook for post_set_output

- pkg/generate/code/set_sdk.go
- pkg/generate/config/resource.go
- pkg/model/crd.go
- scripts/build-controller.sh
- templates/cmd/controller/main.go.tpl
- templates/config/crd/kustomization.yaml.tpl
- templates/pkg/resource/descriptor.go.tpl
- templates/pkg/resource/manager.go.tpl
- templates/pkg/resource/manager_factory.go.tpl
- templates/pkg/resource/registry.go.tpl
- templates/pkg/resource/resource.go.tpl
Issue #, if available: 
- Store `NameField` as part of each CRD - for use in templates
- Add the API scheme to each controller
- Provide each controller with permissions to access the `AdoptedResource` CRD
- Provide method to override resource object meta
> Adopted resource template changes

- go.mod
- go.sum
- pkg/generate/ack/runtime_test.go
Updates our go.mod reference to runtime v0.1.0 (adopted resource
reconciler) and updates our runtime_test.go to implement the runtime
v0.1.0 AWSResourceDescriptor interface.
> pin code-generator to runtime v0.1.0

- go.mod
- pkg/generate/generator.go
- pkg/generate/mq_test.go
- pkg/generate/testdata/models/apis/mq/0000-00-00/generator.yaml
- pkg/model/crd.go
- pkg/model/field.go
When designing the `pkg/generate/config.FieldConfig` object, we really
only thought about (and tested for) "top-level fields". In other words,
fields that were on the CR's `Spec` or `Status` objects.
However, as we've added more configurability to the code-generator
regarding fields -- including marking fields as printable or secrets --
we're now limited substantially by our initial implementation that only
allows referring to top-level fields.
For example, we cannot mark a field as being a secret field if that
field is a subfield of one of these top-level fields. Concretely, this
means that with the existing generator configuration, we cannot support
configuring AmazonMQ's `Broker` CRD's `Spec.Users.Password` field as a
SecretKeyReference because `Password` is not a top-level field. It …
> allow "nested fields" to be configured

- templates/config/samples/sample.yaml.tpl
Signed-off-by: Jose R. Gonzalez <josegonzalez89@gmail.com>
Hi folks! 
I inadvertently left in a hard-coded reference to the S3 APIVersion for the samples that are auto-generated from olmconfig. The result is that I was ending up with samples for kinds that weren't organized under the correct contextual APIVersion (in my case, I've been testing OLM generation against SageMaker as it has a wide variety of CRDs).
Discovered this bug in relation to the work being done here: https://github.com/aws-controllers-k8s/community/issues/744 though it's not directly related to the goal of that issue (i.e. that bug should not be closed in relation to this PR).
**By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> Replace hardcoded APIVersion with contextual APIVersion

- templates/config/manifests/bases/clusterserviceversion.yaml.tpl
Signed-off-by: Jose R. Gonzalez <josegonzalez89@gmail.com>
**Issue #, if available:**
No Issue created in association with this as it's a fairly minor bugfix.
The `ClusterServiceVersion.spec.icon[0]` values had a spelling/case error that was preventing the bundles from being generated with the right values. This corrects those two bugs.
**By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**
:+1:
> Fix case and spelling of CSV icon-related keys and adjust description template var for a cleaner olmconfig

- pkg/model/crd.go
In `crd.go.tpl` template file `field.Names.Camel` is used this results in `replicationGroupID` to be used as spec param rather than `replicationGroupId`.
Updating this method to be consistent with `crd.go.tpl` and to unblock elasticache code generation. 
Without fix
```
func (r *resource) SetIdentifiers(identifier *ackv1alpha1.AWSIdentifiers) error {
if identifier.NameOrID == nil {
return ackerrors.MissingNameIdentifier
}
r.ko.Spec.ReplicationGroupId = identifier.NameOrID
return nil
}
```
With fix
```
func (r *resource) SetIdentifiers(identifier *ackv1alpha1.AWSIdentifiers) error {
if identifier.NameOrID == nil {
return ackerrors.MissingNameIdentifier
}
r.ko.Spec.ReplicationGroupID = identifier.NameOrID
return nil
}
```
By submitting this pull request, I confirm that my contribution is …
> Use camel case name in SpecIdentifierField

- pkg/model/sdk_helper.go
When generating controllers for the CloudFront API using the crossplane pipeline, I realized that we do not account for CRD List types (e.g., `DistributionList`) in `model.HasConflictingTypeName`, which results in such types being declared multiple times in generated code. This PR attempts to prevent this.
> Add check for CRD list types in model.HasConflictingTypeName

- pkg/generate/ack/hook.go
- templates/pkg/resource/sdk.go.tpl
- templates/pkg/resource/sdk_find_get_attributes.go.tpl
- templates/pkg/resource/sdk_find_read_many.go.tpl
- templates/pkg/resource/sdk_find_read_one.go.tpl
- templates/pkg/resource/sdk_update.go.tpl
Adds the `post_build_request` hooks which are called AFTER the call to construct the Input shape but BEFORE the API operation. 
```
resources:
ScalableTarget:
hooks:
sdk_read_many_post_build_request:
code: rm.customDescribeScalableTarget(ctx, r, input)
```
Fixed the bug in applicationAutoscaling where one could not create a `ScalableTarget` resource which would throw the following error - 
```
Reconciler error	{"controller": "scalabletarget", "request": "default/dynamodb-scalable-target-2ir12cp", "error": "ValidationException: Scalable dimension cannot be provided without resource IDs."}
```
> Add hooks after input request creation, but before request is submitted.

- pkg/generate/generator.go
- pkg/model/type_def.go
- templates/apis/type_def.go.tpl
Adds documentation to the nested field types in `apis/$VERSION/types.go`
output for the structs and the fields within those structs. The fields
within the structs are modeled with the `pkg/model.Attr` struct, so I
added a `Shape` field to that in order to bring in the aws-sdk-go
`private/model/api.Shape` that has a `Documentation` field on it...
Tested on ECR controller and works properly even for nested fields:
```
[jaypipes@thelio ecr-controller]$ git diff apis/v1alpha1/types.go
diff --git a/apis/v1alpha1/types.go b/apis/v1alpha1/types.go
index d384431..39c4f13 100644
--- a/apis/v1alpha1/types.go
+++ b/apis/v1alpha1/types.go
@@ -16,35 +16,81 @@
+// The encryption configuration for the repository. This determines how the
+// contents of your repository are encrypted at rest.
+//
+// By …
```
> add doc support to nested field types

- templates/config/scorecard/patches/basic.config.yaml
- templates/config/scorecard/patches/olm.config.yaml
**Issue #, if available:**
N/A
The Operator SDK Scorecard tests run against an OLM bundle to help validate that the contents looks appropriate. The scorecard container appears to be built with an image tag corresponding with the version of Operator SDK that's used.
The dependency installation script has been updated - https://github.com/aws-controllers-k8s/community/pull/762 - and this PR updates the code generated to match.
In addition two of the built-in tests are currently out of scope for the code-generator logic.
* **olm-crds-have-resources-test** - I believe this to be out of scope because this is a cloud integration operator, and therefore each controller is unlikely to have local resources that OLM should need to represent via the console.
* …
> Update Operator SDK scorecard image tags and disable two scorecard test tags

- templates/crossplane/apis/types.go.tpl
- templates/crossplane/pkg/controller.go.tpl
- templates/pkg/resource/sdk.go.tpl
- templates/pkg/resource/sdk_find_get_attributes.go.tpl
- templates/pkg/resource/sdk_find_read_many.go.tpl
- templates/pkg/resource/sdk_find_read_one.go.tpl
- templates/pkg/resource/sdk_update.go.tpl
- templates/pkg/resource/sdk_update_set_attributes.go.tpl
Description of changes: `Name` can return the name of the call with a date as we experienced in `CloudFront` service (like `GetDistribution2020_05_31WithContext`). Tested this statement with `rds` service and no change was seen.
I made the change in both ACK and Crossplane pipelines. It shouldn't affect the existing controllers.
> Use ExportedName property of operation calls instead of Name

- templates/pkg/resource/resource.go.tpl
* Using '_' variable for working around the unused import build time error.
Sometimes the following code does not use the block with `ackerrors.MissingNameIdentifier` in resource.go.tpl and generates the build time errors.
```
func (r *resource) SetIdentifiers(identifier *ackv1alpha1.AWSIdentifiers) error {
{{- if $idField := .CRD.SpecIdentifierField }}
if identifier.NameOrID == nil {
return ackerrors.MissingNameIdentifier
}
r.ko.Spec.{{ $idField }} = identifier.NameOrID
{{- else }}
r.ko.Status.ACKResourceMetadata.ARN = identifier.ARN
{{- end }}
return nil
}
```
> Using '_' variable for working around the unused import build time error.

- go.mod
- templates/cmd/controller/main.go.tpl
- templates/config/controller/deployment.yaml.tpl
- templates/helm/templates/deployment.yaml
- templates/helm/values.yaml.tpl
Add ability to listen to specific namespace for service controllers
Tested locally for both positive and negative case
aws-controllers-k8s/community#686
Related PR:
https://github.com/aws-controllers-k8s/runtime/pull/12
> Namespace scope service controllers 

- pkg/generate/code/set_resource.go
Part of https://github.com/aws-controllers-k8s/community/issues/773
- panic if `list_operation.matchFields` configuration contains an element that is not part of Spec or Status fields
> panic if matchFieldName config contains an element that is not part of Spec or Status fields

- pkg/generate/ack/controller.go
- pkg/generate/code/equal.go
- pkg/generate/code/equal_test.go
- templates/pkg/compare/struct.go.tpl
Issue https://github.com/aws-controllers-k8s/community/issues/757
Adds new code generation functions to `pkg/generate/code` that output Go code that checks the equality of two types. The generated code returns false at the first observed difference. The generated code re-uses the comparison functions for all nested fields of struct type.
This package will be imported and used by the generated `delta.go` file
that helps in comparing CRD fields.
For field of scalar type code looks like:
```go
if ackcompare.HasNilDifference(a.RegistryID, b.RegistryID) {
return false
} else if a.RegistryID != nil && b.RegistryID != nil {
if *a.RegistryID != *b.RegistryID {
return false
}
}
```
For fields of type struct code look like:
```go
if …
```
> Add code generation for type comparison

- go.mod
- go.sum
- templates/helm/templates/deployment.yaml
- templates/helm/values.yaml.tpl
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/787
Tested using sagemaker-controller
```
k get pods -n ack-system -ojson
"spec": {
"containers": [
{
"args": [
"--aws-account-id",
"$(AWS_ACCOUNT_ID)",
"--aws-region",
"$(AWS_REGION)",
"--enable-development-logging",
"$(ACK_ENABLE_DEVELOPMENT_LOGGING)",
"--log-level",
"$(ACK_LOG_LEVEL)",
"--resource-tags",
"$(ACK_RESOURCE_TAGS)",
"--watch-namespace",
"$(ACK_WATCH_NAMESPACE)"
],
"command": [
"./bin/controller"
],
"env": [
{
"name": "K8S_NAMESPACE",
"valueFrom": {
"fieldRef": {
"apiVersion": "v1",
"fieldPath": "metadata.namespace"
}
}
},
{
"name": "AWS_ACCOUNT_ID",
"value": "xxx"
},
{
"name": "AWS_REGION",
"value": "us-west-2"
},
{
"name": "ACK_WATCH_NAMESPACE"
},
{
"name": "ACK_ENABLE_DEVELOPMENT_LOGGING", …
```
> helm chart: add log and accountid

- pkg/generate/ack/release.go
- templates/helm/templates/service.yaml
- templates/helm/values.yaml.tpl
Adding ClusterIP service in helm chart to expose controller metrics.
It is much simpler and easier to update prometheus scraping configuration with a static endpoint.
> Adding ClusterIP service in helm chart to expose controller metrics.

- pkg/generate/config/field.go
- pkg/model/crd.go
- templates/pkg/resource/sdk.go.tpl
- templates/pkg/resource/sdk_update.go.tpl
Add an advisory condition if an immutable field is modified.
```
Conditions:
Status:     False
Type:       ACK.Terminal
Status:     True
Type:       ACK.ResourceSynced
Status:     False
Type:       ACK.Recoverable
Message:    Immutable Spec fields have been modified : AtRestEncryptionEnabled,TransitEncryptionEnabled
Status:     True
Type:       ACK.Advisory
Description:  Reinvent replication group
```
Clears the status upon fixing the field in the manifest
```
Conditions:
Status:     False
Type:       ACK.Terminal
Status:     True
Type:       ACK.ResourceSynced
Status:     False
Type:       ACK.Recoverable
Description:  Reinvent replication group
```
This commit allows one to specify immutable fields in `generator.yaml`.
```
TransitEncryptionEnabled:
is_immutable: true …
```
> Immutable fields advisory

- templates/crossplane/pkg/controller.go.tpl
Description of changes: Fixes the controller template for attribute-based APIs
> crossplane: fix the controller template for attribute-based APIs

- templates/helm/templates/metrics-service.yaml
- templates/helm/values.yaml.tpl
Explicitly mentioning 'metrics' for the ACK controller service.
Sample dry-run putput:
```
apiVersion: v1
kind: Service
metadata:
name: somename-ack-apigatewayv2-controller-metrics
namespace: default
labels:
app.kubernetes.io/name: ack-apigatewayv2-controller
app.kubernetes.io/instance: somename
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/version: "v0.0.2"
k8s-app: ack-apigatewayv2-controller
helm.sh/chart: ack-apigatewayv2-controller-v0.0.2
control-plane: controller
spec:
selector:
app.kubernetes.io/name: ack-apigatewayv2-controller
app.kubernetes.io/instance: somename
app.kubernetes.io/managed-by: Helm
k8s-app: ack-apigatewayv2-controller
type: ClusterIP
ports:
- name: metricsport
port: 8080
targetPort: 8080
protocol: TCP
```
By submitting this pull …
> Explicitly mentioning 'metrics' for the ACK controller service.

- pkg/generate/code/set_resource_test.go
- pkg/generate/code/set_sdk_test.go
- pkg/generate/elasticache_test.go
- pkg/generate/testdata/models/apis/elasticache/0000-00-00/api-2.json
- pkg/generate/testdata/models/apis/elasticache/0000-00-00/docs-2.json
- pkg/generate/testdata/models/apis/elasticache/0000-00-00/generator.yaml
ElastiCache would use new AWS SDK Go to include new features like LogDelivery which are currently not part of `elasticache-controller`. This PR updates the test data used in code generator for Elasticache tests.
Additionally I have updated `generator.yaml` to be inline with one being used in `elasticache-controller`. Updated unit tests which use `CacheCluster` resource to `ReplicationGroup`.
> Update ElastiCache CodeGen test based on new SDK

- pkg/generate/config/field.go
- pkg/model/printer_column.go
Issue N/A
In some CRDs like `GlobalTable` adding a `is_printable: true` to the `GlobalTableStatus` causes `kubectl get` to print very large/redundant column names.
- This patch adds a new config to allow overriding kubebuilder `printcolumn:name`
- Adds `metav1.Time` to the `acceptableColumnMap`
> Add a new config to override kubebuilder `printcolumn:name`

- templates/crossplane/apis/crd.go.tpl
This is required to fix https://github.com/crossplane/provider-aws/issues/697
In the vast majority of resources a spec is required, so I'd like to mark it as such. I believe that in the edge cases where the spec really contains only optional fields it's possible to write `spec: {}`.
We prefer not to mark status fields as required, since resources will always exist at some point without their status and we consider 'requiredness' to be more of a human-facing constraint than a software-facing constraint that our managed resource controllers should be subject to.
> crossplane: Mark spec as required, status.atProvider as optional

- templates/pkg/resource/manager.go.tpl
Issue https://github.com/aws-controllers-k8s/community/issues/807
For some controllers we noticed an incorrect reconciliation behaviour
when a custom hook code was returning a `RequeueNeededAfter` error.
More precisely `resourceManager.ReadOne` was not returning the correct
observed state when `sdkFind` returns with an error. Which was causing
the reconciler to patch to wrong state (`desird` instead `observed`).
This patch fixes this issue by passing the correct observed state to `onError`.
> Patch the correct observed state after a `rm.ReadOne` call

- pkg/generate/codedeploy_test.go
- pkg/generate/config/field.go
- pkg/generate/config/resource.go
- pkg/generate/testdata/models/apis/codedeploy/0000-00-00/generator.yaml
- pkg/model/crd.go
- pkg/model/printer_column.go
Issue https://github.com/aws-controllers-k8s/community/issues/823
This patch introduce a new generator configuration under resource
configuration, mainly to tune the `kubebuilder:printcolumn` marker
comments generation.
More precisely we add `PrintConfig` struct that contains one field
called `OrderBy` used to intruct the code generator how to sort the
`kubebuilder:printcolumn` marker comments.
e.g configuration:
```yaml
resources:
Deployment:
print:
order_by: JSONPath
```
> Add a new generator config to change `PrinterColumn` sort function

- templates/crossplane/pkg/controller.go.tpl
Description of changes: Remove unnecessary error handling in Update because it's already handled in return statement. Manually tested.
> crossplane: remove unnecessary error handling in Update

- pkg/generate/config/field.go
- pkg/model/printer_column.go
- templates/apis/crd.go.tpl
Issue https://github.com/aws-controllers-k8s/community/issues/821
This patch introduces a new config field called "Standard" under 
`PrintFieldConfig` to indicates whether the column is of priority 0 or 1.
> Add a new config to override `kubebuilder:printcolumn` priority

- pkg/generate/code/set_sdk.go
- pkg/generate/code/set_sdk_test.go
- pkg/generate/elasticache_test.go
- pkg/generate/testdata/models/apis/elasticache/0000-00-00/generator.yaml
- pkg/model/field.go
- pkg/model/types.go
Issue: https://github.com/aws-controllers-k8s/community/issues/828
With this code change, when a field of type slice
is configured as secret type inside Generator config,
then the generated CRD yaml allows specifying multiple k8s secret values
for that field in input yaml and generated sdk code supplies these values
to the resource API input field as slice type.
Added unit tests to test the scenario.
Details on resultant generated code:
Taking ElastiCache User API has `passwords` filed as example:
ElastiCache User API has `passwords` filed of type `[]*string` in the API input. [Reference API docs](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/elasticache/create-user.html)
When this field is configured as secret type inside Generator config:
``` …
```
> Extend ack-generate to generate slice with elements of type K8s Secret

- pkg/generate/code/set_resource.go
- pkg/generate/code/set_resource_test.go
- pkg/generate/config/operation.go
- pkg/generate/testdata/models/apis/dynamodb/0000-00-00/generator.yaml
- pkg/model/crd.go
Issue N/A
In some AWS APIs `Describe` operations output contains the
wanted information in a wrapper field like `TableDescription` and
`GlobalTableDescription` ... However in some other APIs for the same
operation type, the wanted information is wrapped in different nested
object, like `BackupDescription.BackupDetails` for example.
This patch adds a new operation configuration that instructs the
code-generator to use a specific field path, in order to find the
struct that contains the information we want to set the output from.
> Add a new operation config to override the `SetOutput` wrapper field

- pkg/model/crd.go
- templates/apis/crd.go.tpl
Replaces the comment block for CRDs with the documentation of the resource shape from the AWS SDK.
> Add base CRD documentation

- pkg/generate/config/resource.go
- pkg/model/crd.go
- templates/apis/crd.go.tpl
Issue: https://github.com/aws-controllers-k8s/community/issues/822
Since All kubernetes resources have a `.metadata.creationTimestamp` field,
we need a way to instruct the code generator to generate kubebuilder
marker comments that will append the AGE field the `kubectl get`
response.
This patch extends `Resource.PrintConfig` to allow configuring the
`ack-generate` to generate such marker comments.
> Add a new generator config to append an Age `printcolumn`

- Makefile
- cmd/ack-generate/command/apis.go
- cmd/ack-generate/command/root.go
- cmd/ack-generate/main.go
- pkg/generate/ack/output.go
- pkg/version/version.go
Issue https://github.com/aws-controllers-k8s/community/issues/809
This patch adds a cobra `PostRunE` function that writes generator
parameters, output metadata and generated files checksum, to a
file within the API versions directory.
> Add a cobra `PostRunE` to save generation metadata 

- pkg/model/crd.go
@kumargauravsharma noticed that when generating the User resource
package in the elasticache-controller, sometimes he saw the Identifier
field be User.Spec.UserID. Other times it was User.Spec.UserName. Turns
out in the `pkg/model.CRD:SpecIdentifierField()` method, we were looping
over the `CRD.SpecFields` map keys (which are not ordered) instead of a
sorted list of spec field names, which is returned by the
`CRD.SpecFieldNames()` method.
By submitting this pull request, I confirm that my contribution is made under the
terms of the Apache 2.0 license.
> fix: use deterministic sort for identifier field

- Makefile
- pkg/generate/ack/controller.go
- pkg/generate/config/config.go
- pkg/generate/generator.go
- templates/pkg/resource/registry.go.tpl
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/745
If any of the fields defined in the generator are set to `is_secret: True`, then add `get;list;watch` permissions for secrets on the controller `ClusterRole`
Output into `cluster-role-controller.yaml`:
```yaml
- apiGroups:
- ""
resources:
- secrets
verbs:
- get
- list
- watch
```
> Conditionally allow view secrets on ClusterRole

- pkg/generate/ack/controller.go
- pkg/generate/code/check.go
- pkg/generate/config/resource.go
- pkg/generate/crossplane/crossplane.go
- pkg/generate/sagemaker_test.go
- pkg/generate/testdata/models/apis/sagemaker/0000-00-00/generator.yaml
- templates/crossplane/pkg/conversions.go.tpl
- templates/pkg/resource/sdk_find_get_attributes.go.tpl
- templates/pkg/resource/sdk_find_read_many.go.tpl
- templates/pkg/resource/sdk_find_read_one.go.tpl
- templates/pkg/resource/sdk_update_set_attributes.go.tpl
https://github.com/aws-controllers-k8s/community/issues/840
Add support for suffix exception checking. Also added Sagemaker tests for prefix and suffix exceptions.
> Support suffix exception

- go.mod
- go.sum
- pkg/generate/ack/runtime_test.go
- pkg/generate/mq_test.go
- pkg/model/crd.go
- templates/pkg/resource/manager.go.tpl
- templates/pkg/resource/sdk.go.tpl
- templates/pkg/resource/sdk_find_get_attributes.go.tpl
- templates/pkg/resource/sdk_find_read_many.go.tpl
- templates/pkg/resource/sdk_find_read_one.go.tpl
- templates/pkg/resource/sdk_update.go.tpl
Updates the sdk.go-specific templates to take advantage of the new
ACK runtime logger that is embedded in all Context structs passed from
the ACK runtime v0.2.3 release and after.
In working these log traces into the various sdkXXX methods, I took this
opportunity to clean up some of the ugly template conditionals in these methods
that checked to see whether an Output shape was being referenced as a
variable after calling the aws-sdk-go API calls and setting the
associated variable name to `_` in order to prevent `unused variable
declared` compilation failures.
The template code for handling this used to look like this:
```
{{ $createCode := GoCodeSetCreateOutput .CRD "resp" "ko" 1 false }}
{{ if not ( Empty $createCode ) }}resp{{ else }}_{{ end }}, respErr := rm.sdkapi.{{ …
```
> trace sdk.go resource manager methods

- pkg/generate/ack/controller.go
- pkg/generate/ack/hook.go
- pkg/generate/ack/hook_test.go
Issue #, https://github.com/aws-controllers-k8s/community/issues/838
This PR enables support for crd variables and controller functions and hooks within hook templates.
The hook templates insides the service controllers can be similar to the templates that are inside code-generator.
For example, following hook template refers `.CRD` variable, invokes controller function `GoCodeSetCreateOutput` and has its own extension hook `sdk_addon_set_output_post_populate`:
and it can be used as hook inside generator.yaml for a resource:
```
{{ $outputShape := .CRD.GetOutputShape .CRD.Ops.Create }}
// This method copies the data from given {{ $outputShape.ShapeName }} by populating it
// into copy of supplied resource and returns that.
func (rm *resourceManager) set{{ …
```
> Enable crd variables and controller functions and hooks within hook templates

- pkg/generate/code/set_resource.go
- pkg/generate/code/set_resource_test.go
- pkg/model/crd.go
This PR also adds a method `GetOutputShape` to crd which provides output shape
For example, `CreateReplicationGroupOutput`, `ModifyReplicationGroupOutput` wrap `ReplicationGroup` object.
This method is useful in creating reusable code which populates the fields from wrapped object to `ko`.
> Add CRD method to get OutputShape

- templates/pkg/resource/sdk.go.tpl
Code generator fails when custom implementation is provided for create scenario
Steps to reproduce:
1. Run `make build-ack-generate && make build-controller SERVICE=$SERVICE`
2. Observe: 
> /Users/kumargsh/ws/github_ws/go/src/github.com/aws-controllers-k8s/elasticache-controller/pkg/resource/snapshot/sdk.go:311:17: expected ';', found created
Error: not all generators ran successfully
3. Corresponding `sdk.go` code:
> 	exit := rlog.Trace("rm.sdkCreate")
defer exit(err)created, err = rm.CustomCreateSnapshot(ctx, desired)
if created != nil || err != nil {
return created, err
}
Observe, missing newline after `defer exit(err)`
Updated the template.
Testing
* `make test` passed.
* ElastiCache service controller gets generated fine.
By submitting …
> fix template for create custom implementation scenario

- templates/pkg/resource/sdk.go.tpl
- templates/pkg/resource/sdk_update.go.tpl
A [previous commit][0] that changed the ACK pkg/resource templates
introduced an error for controllers that have CREATE or UPDATE
implementations where the Output shape from the operation sets no fields
on the CR.
In these cases, attempting to build these controllers was resulting in a
build failure, like this for the RDS controller:
```
pkg/resource/db_parameter_group/sdk.go:205:6: resp declared but not used
```
This corrects that by using a blanking technique immediately after the
variable declaration:
```
var resp *SomeSDKShape; _ = resp;
```
[0]: a42b4a1a9081824ff60a29b8a5f31ccf79026372
> prevent unused variable error

- templates/pkg/resource/sdk.go.tpl
Remove duplicate `aws-sdk-go/$service` import. It is already imported in L14 with the alias `svcsdk`
> Remove duplicate `aws-sdk-go/$service` import

- pkg/generate/mq_test.go
- pkg/model/crd.go
- templates/pkg/resource/resource.go.tpl
Add the missing `ReplaceConditions` method introduced in https://github.com/aws-controllers-k8s/runtime/pull/24 .
Fix a import path error introduced in https://github.com/aws-controllers-k8s/code-generator/pull/102
> Fix missing replace conditions method

- go.mod
- go.sum
- pkg/generate/ack/runtime_test.go
Brings the ACK code-generator into alignment with new features in ACK
runtime v0.3.0, including the new ConditionManager interface and the new
RequeueOnSuccessSeconds method of AWSResourceManagerFactory.
Related: aws-controllers-k8s/code-generator#104
> align code-generator to ACK runtime v0.3.0

- pkg/generate/config/resource.go
- pkg/generate/sagemaker_test.go
- pkg/generate/testdata/models/apis/sagemaker/0000-00-00/generator.yaml
- pkg/model/crd.go
- templates/pkg/resource/manager.go.tpl
- templates/pkg/resource/manager_factory.go.tpl
- templates/pkg/resource/sdk.go.tpl
This PR is one of two to implement [Issue #826](https://github.com/aws-controllers-k8s/community/issues/826) 
[Link to the runtime PR](https://github.com/aws-controllers-k8s/runtime/pull/23)
I tested the change by enabling it for applicationAutoscaling (ScalableTarget) - [you can check the generated code on this branch just for reference. ](https://github.com/aws-controllers-k8s/applicationautoscaling-controller/pull/21)
Added 2 unit tests for the cases where the requeue duration is specified in the config file and where it isnt. Locally tested the unit test fails for incorrect assertions. successful result as follows - 
```
(base) 147ddacd269c:code-generator mbaijal$ make test
go test -tags codegen ./...
?   	github.com/aws-controllers-k8s/code-generator/cmd/ack-generate	[no test files] …
```
> Provide an option to configure a resource to requeue infinitely (Issue #826)

- pkg/names/names.go
- Add OIDC as an accepted initialism
- Prevent "Identity" from being incorrectly capitalised
> Add OIDC and identity to initialisms

- cmd/ack-generate/command/apis.go
- pkg/util/file.go
Part of aws-controllers-k8s/community#835
Adding some logic to create copies of the `generator.yaml` within the
apis versions directories. These generator.yaml files we be reused by
the conversion webhook generator to understand the difference between
each two different API versions.
This patch Also adds a new utility function to copy files from a
source to a destination path.
> Copy `generator.yaml` to apis/version directory

- Makefile
- Bump `ack-generate` version in Makefile
> Bump ack-generate `VERSION` variable

- pkg/generate/ack/controller.go
- pkg/generate/code/set_resource.go
- pkg/generate/code/set_resource_test.go
- pkg/generate/config/operation.go
- pkg/generate/testdata/models/apis/rds/0000-00-00/generator.yaml
- pkg/model/crd.go
- templates/pkg/resource/resource.go.tpl
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/842
This pull request introduces a smarter system for detecting resource primary identifiers by using the fields from the `ReadOne` (or optionally `ReadMany`) operations.
It detects if a field is attempting to use the resource ARN and will set the status metadata to the corresponding identifier element. Otherwise, it will search through each of the required fields in the operation to attempt to identify the "primary" identifier field (such as `*Name`, `Name`, `*ID`). All other fields in the operation can be configured through the use of the new `AdditionalKeys` map (https://github.com/aws-controllers-k8s/runtime/pull/13/files). Optionally, the primary identifier field can be configured …
> Generate resource identifiers from `ReadOne` or `ReadMany`

- templates/cmd/controller/main.go.tpl
Part of https://github.com/aws-controllers-k8s/community/issues/835
- Setup webhooks on controller startup
- Extract host and port values from `--webhook-server-addr` and pass them
to `controller-runtime.NewManager` options 
> Setup webhooks on controller startup

- pkg/generate/code/set_resource.go
- pkg/generate/code/set_resource_test.go
Related to https://github.com/aws-controllers-k8s/code-generator/pull/105 and https://github.com/aws-controllers-k8s/runtime/pull/13
- replace nil pointer checks with string zero value checks
- replace `string` value assignment with `string` ptr assignments
> Correct type mismatch errors in `SetResourceIdentifiers` generated code

- pkg/generate/code/set_resource.go
Related to https://github.com/aws-controllers-k8s/code-generator/pull/115
For some controllers we use `ReadMany` operations to read resource current
state. For these operations we need to lookup for identifiers ending with 
`Names` and not `Name`. e.g `RepositoryNames` in `DescribeRepositories`
operation.
- Add primary identifiers for `ReadMany` operations
> Add primary identifiers for `ReadMany` operations

- pkg/generate/code/set_resource.go
- pkg/generate/code/set_resource_test.go
The code that outputs Go code that sets `Spec` or `Status` fields to a
resource identifier field was not accounting for cases where we renamed
the field. Such is the case for many of the RDS controller's resources,
since all the identifier fields for all resources are "de-stuttured" by
renaming, for example, `DBSubnetGroupName` to just `Name` or
`DBClusterParameterGroupName` to just `Name`.
This patch simply ensures we account for renamed fields in the Spec and
Status during calls to `pkg/generate/code.SetResourceIdentifiers` and
adds a unit test to ensure we don't regress in the future.
Issue aws-controllers-k8s/community#852
> handle renamed fields for resource identifiers

- Makefile
- go.mod
- go.sum
- pkg/generate/ack/runtime_test.go
Adds a simple compile-time test for pinning code-gen to the ACK runtime
v0.4.0 so that we can bring the code generated by these templates
in-line with the ACK runtime v0.4.0 (which added support for
AWSIdentifiers.AdditionalKeys and the pkg/webhook stuff referred to from
templates/cmd/controller/main.go.tpl)
> pin code-gen to ACK runtime v0.4.0

- cmd/ack-generate/command/apis.go
- cmd/ack-generate/command/common.go
- cmd/ack-generate/command/controller.go
- cmd/ack-generate/command/crossplane.go
- cmd/ack-generate/command/olm.go
- cmd/ack-generate/command/release.go
Issue N/A
`ack-generate` uses go-git to clone and fetch repository tags, these
actions are time consuming (more than a minute for cloning) and do
not tolerate interruption (ctrl+C). Forcing a command to exit when it's
running a `git.Clone` or a `git.FetchTags` cause the process to write
incomplete data on disk,  therefore re-running `ack-generate` will
always return an error. The only solution for this problem is to delete
the local sdk cache and let `ack-generate` reclone (without interruption)
This patch adds a graceful cancellation system for `ack-generate`
subcommads. Which will allow users to safely ctrl+C and re-run their
commands without any errors.
> Graceful cancellation for network dependent commands

- pkg/generate/config/field.go
- pkg/model/printer_column.go
Issue N/A
This patch adds a new option `Index` for print column configuration.
Setting an index for a field and `resource.print.sortBy` to `index` will
intruct the code generator to sort the `kubebuilder:printcolumns` by the
`Index` value.
> Add a new sort option for `kubebuilder:printcolumns` marker comments

- Dockerfile
- Dockerfile.local
- Makefile
- scripts/build-controller-image.sh
- scripts/build-controller-release.sh
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/860
Migrates the `build-controller-image` and `build-controller-release` scripts and Makefile targets from the `community` repository. Also migrates the `Dockerfile` and `Dockerfile.local` files for building the release images.
> Migrate image build and release scripts from `community`

- Makefile
- go.mod
- templates/pkg/resource/manager.go.tpl
- templates/pkg/resource/sdk.go.tpl
aws-controllers-k8s/community#836
This PR is to related to https://github.com/aws-controllers-k8s/runtime/pull/21
It makes the code-generator changes for delete api as discussed under: https://github.com/aws-controllers-k8s/runtime/pull/21#discussion_r655729649
Testing:
* `make test` passed.
> Returning the latest resource from the Delete() call

- pkg/model/model.go
Issue N/A
This patch fixes a bug where `ack-generate` used to  prepend a `[]`
prefix to any map of structs (example `Route_SDK.RequestParameters`
in apigatewayv2)
Also in the same PR, moving the GoType cleanup logic to a separate 
function `model.getShapeCleanGoType` to simplify `model.GetTypeDefs`
code.
> Recursively build a clean GoType for nested maps and arrays

- Makefile
- go.mod
- go.sum
- pkg/generate/ack/runtime_test.go
Issue N/A
- Adds a test case for pinning code-generator to the ACK runtime v0.6.0.
- Bump `ack-generate` version to v0.6.0
> pin code-gen to ACK runtime 0.6.0

- pkg/generate/ack/hook.go
- templates/pkg/resource/sdk.go.tpl
Ability for service controllers to add code (additional functions, variables etc as needed) to sdk.go file using hooks as extension mechanism.
This PR adds `sdk_addon` hook to `sdk.go.tpl`. Using this hook, service controllers can append code to a custom resource's `sdk.go` file. It will help in placing reusable code/functions which are generated dynamically using hook templates.
Following PR contains changes showcasing how this facility helps service controllers auto generate reusable code: https://github.com/aws-controllers-k8s/elasticache-controller/pull/36
> Add sdk addon hook

- templates/apis/crd.go.tpl
Issue N/A
- Mark status fields as optional using `+kubebuilder:validation:Optional` marker comment
> Mark status fields as optional

- .github/workflows/version-check.yaml
- Makefile
- scripts/check-versions.sh
Adds a script that compares the `aws-controllers-k8s/runtime` version listed in the `go.mod` is identical to the `VERSION` variable in the `Makefile`. This way we can ensure the generation metadata is kept in line with the version of the runtime it was built against.
/assign @A-Hilaly 
> Add script and Github workflow for ensuring version in sync

- Makefile
- go.mod
- go.sum
- pkg/generate/ack/runtime_test.go
- pkg/generate/code/set_sdk.go
- pkg/generate/config/resource.go
- templates/pkg/resource/sdk.go.tpl
For now secret errors would be terminal code to
be consistent with ACK behavior.
```
Conditions:
Message:  kubernetes secret not found
Status:   True
Type:     ACK.Terminal
```
Runtime PR - https://github.com/aws-controllers-k8s/runtime/pull/33
> Secret errors to be terminal code

- templates/helm/templates/deployment.yaml
- templates/helm/values.yaml.tpl
https://github.com/aws-controllers-k8s/community/issues/871
Updates `codegenerator/templates/helm/templates/deployment.yaml.tpl` and `codegenerator/templates/helm/values.yaml.tpl `to support `AWS_ENDPOINT_URL`
> Add AWS_ENDPOINT_URL to Helm chart templates 

- pkg/generate/ack/controller.go
- pkg/generate/code/set_resource.go
- pkg/generate/code/set_resource_test.go
- pkg/generate/crossplane/crossplane.go
- templates/crossplane/pkg/controller.go.tpl
- templates/crossplane/pkg/sdk_find_read_many.go.tpl
- templates/crossplane/pkg/sdk_find_read_one.go.tpl
- templates/pkg/resource/sdk.go.tpl
- templates/pkg/resource/sdk_find_read_many.go.tpl
- templates/pkg/resource/sdk_find_read_one.go.tpl
- templates/pkg/resource/sdk_update.go.tpl
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/812
* Do not restrict Create and Update operation output to only updating the Status of latest k8s resource. This change will allow both Spec and Status of latest object to be updated.
* Removing of conditional "performSpecUpdate" will allow both Spec and Status fields to be updated.
* This will allow server-side-defaults to be populated into the k8s latest object. Server-side-defaults are the default values added by AWS service upon resource creation/update when these optional values were not specified by the user.
------
make test
```
➜  code-generator git:(allow-spec-updates) make test
go test -tags codegen ./...
?       github.com/aws-controllers-k8s/code-generator/cmd/ack-generate …
```
> Remove performSpecUpdate(boolean) from Set<Operation>Output.

- scripts/build-controller-release.sh
Fix the release script to include a reference to the metadata config file path
> Load metadata in release script

- cmd/ack-generate/command/release.go
- scripts/build-controller-release.sh
- templates/helm/Chart.yaml.tpl
- templates/helm/values.yaml.tpl
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/829
* Update `build-controller-release` script to use latest ecr-public repository as image repository
* Update Chart.yaml.tpl for chart name so that helm charts can be properly added as dependencies. (Fixing helm chart semver issue)
* Update values.yaml.tpl to form image url correctly due to latest changes
------
make test successful
```
➜  code-generator git:(new-ecr) make test
go test -tags codegen ./...
?       github.com/aws-controllers-k8s/code-generator/cmd/ack-generate  [no test files]
?       github.com/aws-controllers-k8s/code-generator/cmd/ack-generate/command  [no test files]
ok      github.com/aws-controllers-k8s/code-generator/pkg/generate/ack  0.883s
ok …
```
> Update for helm charts to use latest ecr-public repository.

- scripts/build-controller-release.sh
- scripts/build-controller.sh
Issue #, if available: Fixes https://github.com/aws-controllers-k8s/community/issues/878
Rather than defaulting to a set version of the AWS SDK, this pull request will read the `go.mod` in the service controller's repository and infer the `github.com/aws/aws-sdk-go` version.
> Default `AWS_SDK_GO_VERSION` to go.mod version

- pkg/generate/code/compare_test.go
- pkg/model/crd.go
- pkg/model/model.go
- pkg/model/model_s3_test.go
- pkg/testdata/models/apis/s3/0000-00-00/generator.yaml
Allow the use of member fields contained within other API operations within a resource's spec. For example, `LoggingStatus` for S3 is only in the `PutBucketLogging` operation, but should be settable from spec.
> Allow member fields from other operations in spec

- Makefile
- go.mod
- go.sum
- pkg/generate/ack/runtime_test.go
- templates/pkg/resource/descriptor.go.tpl
Removes the unused AWSResourceDescriptor.UpdateCRStatus that was removed
in ACK runtime v0.8.0
By submitting this pull request, I confirm that my contribution is made under the
terms of the Apache 2.0 license.
> bring in ACK runtime v0.8.0

- pkg/generate/ack/apis.go
- pkg/generate/ack/controller.go
- pkg/generate/code/set_resource.go
- pkg/generate/code/set_sdk.go
Makes `setSDKForStruct` and `setResourceForStruct` public, so that they are accessible for other parts of the generator. Exposes `SetSDKForStruct` as `GoCodeSetSDKForStruct` and `SetResourceForStruct` as `GoCodeSetResourceForStruct` in the generator, and includes `SDKAPI` as a template variable to allow querying of API shapes to use with parameters in the new template methods.
> Expose `SetSDKForStruct` and `SetResourceForStruct` in templates

- pkg/model/crd.go
I believe two loops were left over from refactoring:
* One loop over fieldPathParts have been replaced with recursion. The
current loop will only execute the first element, so we can remove the
loop.
* Another loop over map keys, but we can simply use a map lookup
instead for a bit better performance
There is already a unit test for this code.
> Remove loops from GetWrapperOutputShape

- Makefile
- go.mod
- go.sum
Issue #883, if available:
https://github.com/aws-controllers-k8s/community/issues/883
aws-sdk-go version bump, 1.37.4 -> 1.37.10 to unblock cross-plane.
> aws-sdk-go version bump, 1.37.4 -> 1.37.10

- pkg/names/names.go
- pkg/names/names_test.go
Issue #, if available: [#889](https://github.com/aws-controllers-k8s/community/issues/889)
* Adding DPD and IO to initialisms after generating vpc resource for ec2-controller
* Update unit test
Testing:
* make test ✅
* make build controller SERVICE=ec2 ✅
```
// The VPN tunnel options.
type TunnelOption struct {
DPDTimeoutAction     *string `json:"dpdTimeoutAction,omitempty"`
...
}
type VolumeStatusAttachmentStatus struct {
InstanceID    *string `json:"instanceID,omitempty"`
IOPerformance *string `json:"ioPerformance,omitempty"`
...
} 
```
> add DPD and IO to initialisms

- Makefile
- go.mod
- go.sum
- pkg/generate/ack/runtime_test.go
Update the dependent version of ACK runtime to `v0.9.2` and update the `code-generator` version.
> Update to ACK Runtime `v0.9.2`

- pkg/generate/code/check.go
- pkg/generate/code/common.go
- pkg/generate/code/common_test.go
- pkg/testdata/models/apis/ec2/0000-00-00/generator.yaml
Issue #, if available: [#890](https://github.com/aws-controllers-k8s/community/issues/890)
* This is preliminary work to aid in resolving this issue. A PR will follow to close out this issue completely.
* Adds `getSanitizedMemberPath` helper to **check.go**
* Adds new file `common.go` containing helpers that can be used throughout `code` pkg. These 2 helpers make it easier to extract identifier(s) from a given Shape or CRD
Testing:
* `make test` ✅
> Minor Refactor in `pkg/generate/code`

- scripts/install-operator-sdk.sh
- scripts/olm-build-bundle-image.sh
- scripts/olm-create-bundle.sh
- scripts/olm-publish-bundle-image.sh
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/863
Migrate operator-sdk and olm scripts out of community repo to code-gen repo.
https://github.com/aws-controllers-k8s/community/pull/897
> Add operator-sdk and olm scripts to code-generator repo.

- Makefile
- go.mod
- go.sum
- pkg/generate/ack/controller.go
- pkg/generate/ack/hook.go
- pkg/generate/ack/runtime_test.go
- pkg/generate/code/late_initialize.go
- pkg/generate/code/late_initialize_test.go
- pkg/generate/code/late_intialize_test.go
- pkg/generate/config/field.go
- pkg/testdata/models/apis/ecr/0000-00-00/generator-with-field-config.yaml
- pkg/testdata/models/apis/ecr/0000-00-00/generator-with-late-initialize.yaml
- pkg/testdata/models/apis/ecr/0000-00-00/generator-with-nested-path-late-initialize.yaml
- templates/pkg/resource/manager.go.tpl
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/812
* Initial implementation of `AWSResourceManager.LateInitialize()` method code generator
* Adds two new hooks `late_initialize_pre_read_one` & `late_initialize_post_read_one`
* Introduces new LateInitializeConfig with DelaySeconds as single parameter
* Corresponding runtime PR : https://github.com/aws-controllers-k8s/runtime/pull/37
------------------------------------
Testing
* Unit Tests Successful
```
➜  code-generator git:(li-mlp) ✗ make test
go test -tags codegen ./...
?       github.com/aws-controllers-k8s/code-generator/cmd/ack-generate  [no test files]
?       github.com/aws-controllers-k8s/code-generator/cmd/ack-generate/command  [no test files]
ok …
```
> Initial implementation of AWSResourceManager.LateInitialize() method.

- Makefile
- go.mod
- go.sum
- templates/cmd/controller/main.go.tpl
https://github.com/aws-controllers-k8s/community/issues/896
Import service and get its EndpointsID to pass this into the NewServiceController
> Import Aws service package and pass EndpointsID to serviceController

- pkg/generate/code/compare.go
- pkg/generate/code/compare_test.go
- templates/pkg/resource/delta.go.tpl
Although it's not what I wanted and isn't the most efficient thing we
could do, I'm implementing the slice of struct and map of struct
comparisons using `reflect.DeepEqual`. Long-term, I'd like to enable our
generator-config CompareConfig for nested struct fields, and to do that
we cannot use `reflect.DeepEqual`, however for the time-being, since
slice and map of struct is a hole in our delta logic, I'm pushing up
this workaround.
> use reflect to compare map/slice struct

- pkg/generate/ack/controller.go
- pkg/generate/code/check.go
- pkg/generate/code/check_test.go
- pkg/generate/code/common.go
- templates/pkg/resource/sdk_find_read_many.go.tpl
Issue #, if available: [#890](https://github.com/aws-controllers-k8s/community/issues/890)
* Adds checkRequiredFieldsMissingFromShapeReadMany to `check.go` to handle ReadMany operations without a corresponding ReadOne. 
* The new method will **require resource identifier field** should there exist an *identifier* or *identifierS* field in the ReadMany operation. 
* Eventually `newListRequestPayload` will use this identifier field to populate its request in order to guarantee the ReadMany operation returns the desired resource.
* ex: DescribeVpcs has a VpcIds field. Therefore, Vpc shape should require VpcId, which is part of its status field.
* Updated tests and templates
Testing:
* `make test` ✅
* `make build-controller`  ✅
```
func (rm *resourceManager) sdkFind( …
```
> Implement ReadMany for CheckRequiredFieldsMissingFromShape

- templates/helm/templates/deployment.yaml
- templates/helm/values.yaml.tpl
Fixes a couple tiny issues I saw in generating release artifacts
recently: some rogue whitespace and wrapping comments at 80 chars
> small helm template fixes

- pkg/names/names.go
- pkg/names/names_test.go
* add vlan to initialisms; Subnet resource generates this field
Testing:
* `make test` ✅ 
* `make build-controller` ✅ 
```
type LocalGatewayVirtualInterface struct {
LocalAddress   *string `json:"localAddress,omitempty"`
LocalBGPASN    *int64  `json:"localBGPASN,omitempty"`
LocalGatewayID *string `json:"localGatewayID,omitempty"`
OwnerID        *string `json:"ownerID,omitempty"`
PeerAddress    *string `json:"peerAddress,omitempty"`
PeerBGPASN     *int64  `json:"peerBGPASN,omitempty"`
Tags           []*Tag  `json:"tags,omitempty"`
VLAN           *int64  `json:"vlan,omitempty"`
}
```
> add vlan to initialisms

- Makefile
- scripts/build-controller-release.sh
* With the latest addition of presubmit 'release-test' job, service teams are required to execute 'build-controller-release.sh ' script for a successful PR build. 'build-controller-release.sh' script takes VERSION as required parameter.
* Sagemaker team provided the feedback on how they do not want to worry about controller versions until they are doing an actual release. which is fair. 
* So this code change, introduces a default version 'v0.0.0-non-release-version' which allows for successful release-test for service teams without worrying about what VERSION to use until actual release.
* This code change also adds the validation for the `VERSION` parameter.
Why not use something like `git describe --tags --always --dirty` to generate version ?
* The git command …
> Support default non-release version in build-controller-release.sh

- scripts/build-controller-release.sh
Updates the `build-controller-release.sh` script to check for the latest
Git tag on the target service controller repository before defaulting
the RELEASE_VERSION to `v0.0.0-non-release-version`. This allows
developers to regenerate their service controllers with new ACK runtimes
without overwriting the static manifests' image versions from the latest
published Git tag to `v0.0.0-non-release-version`. For service
controllers that have yet to release any images, the
`v0.0.0-non-release-version` continues to be used.
Before this patch:
```
[jaypipes@thelio code-generator]$ make build-controller SERVICE=rds
building ack-generate ... ok.
==== building rds-controller ====
Copying common custom resource definitions into rds
Building Kubernetes API objects for rds
Generating deepcopy code for …
```
> use latest tag before non-release version

- pkg/generate/code/set_resource.go
- pkg/generate/code/set_resource_test.go
- pkg/testdata/models/apis/sagemaker/0000-00-00/generator.yaml
Closes https://github.com/aws-controllers-k8s/community/issues/909
The SageMaker `ModelPackage` (in some cases) needs to be described using the resource ARN, even though the spec has a `ModelPackageName` and the `DescribeModelPackage` input shape has a `ModelPackageName` field. This pull requests allows the service teams to set the `primary_identifier_field_name` as `"ARN"`, to override the default generator logic in order to set the `ACKResourceMetadata.ARN` field to be `identifier.ARN`. 
Also refactored the identifier code to use the new `FindIdentifiersInShape` common method and to use the `setResourceForScalar` method.
> Allow override resource identifier to ARN

- pkg/generate/code/set_sdk.go
- pkg/generate/code/set_sdk_test.go
- pkg/testdata/models/apis/ec2/0000-00-00/generator.yaml
Issue #, if available: [#891](https://github.com/aws-controllers-k8s/community/issues/891)
* adds `setSDKReadMany` func to SetSDK
* adds unit test
Testing:
* `make test` ✅
* `make build-controller`  ✅
```
// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
r *resource,
) (*svcsdk.DescribeVpcsInput, error) {
res := &svcsdk.DescribeVpcsInput{}
if r.ko.Spec.DryRun != nil {
res.SetDryRun(*r.ko.Spec.DryRun)
}
if r.ko.Status.VPCID != nil {
f4 := []*string{}
f4 = append(f4, r.ko.Status.VPCID)
res.SetVpcIds(f4)
}
return res, nil
}
```
> Implement ReadMany operation for SetSDK generator function

- pkg/names/names.go
- pkg/names/names_test.go
* Add `ami` entry to initialisms with test
> add ami to initialisms

- cmd/ack-generate/command/release.go
- pkg/generate/ack/release.go
- pkg/metadata/service_metadata.go
- pkg/model/multiversion/manager.go
- templates/helm/Chart.yaml.tpl
Use the fields in the service metadata file (`metadata.yaml`) to produce nicer descriptions in the Helm chart. 
> Use `ServiceMetadata` strings in Helm charts

- Dockerfile
* Prepend 'https://proxy.golang.org' to GOPROXY in Dockerfile for building controller image.
* This GoPROXY helps fix the building of controller image during e2e tests. Tested by locally running `make kind-test`
> Prepend 'https://proxy.golang.org' to GOPROXY in Dockerfile for building controller image.

- pkg/generate/config/operation.go
- pkg/model/sdk_helper.go
Allow OperatorType to be a list such that one API can map to multiple operations. 
This is required in certain cases where the same API call maps to both Create and Update operations such as `RegisterScalableTarget` and `PutScalingPolicy`
[Link to ApplicationAutoscaling PR with the related change](https://github.com/aws-controllers-k8s/applicationautoscaling-controller/pull/27)
Note: This change will require all other services to update their generator configs as well. 
https://github.com/aws-controllers-k8s/community/issues/867
The `getOpTypeAndResourceName` method handles each of the following cases same as before in addition to the new case 5- 
1.  the cfg itself is nil
2.  cfg is not nil but opId is not in the cfg
3.  cfg is not nil, the opID is in the cfg but …
> Allow OperatorType to be a list such that one API can map to multiple operations

- templates/pkg/resource/sdk.go.tpl
Provide aws error code(e.g. Validation exception, InvalidParameterValue) in addition to message in the condition message
Testing:
Manually introduced an aws error from sdkDelete and verified it gets updated in conditions
> visibility for AWS err code in addition to message

- templates/pkg/resource/manager.go.tpl
- templates/pkg/resource/sdk.go.tpl
- Update conditions on delete in case of error. Right now the errors from delete are not reflected to the user
- I have added a check to treat all errors as recoverable if the resource is being deleted as I am not sure what is the user experience if the resource hits a terminal condition after its deleted. Please advise
Testing:
Manually introduced an error from sdkDelete and verified it gets updated in conditions
> update conditions on error for delete operation

- pkg/generate/code/common_test.go
Issue #, if available: [#922](https://github.com/aws-controllers-k8s/community/issues/922)
* Increasing test coverage of identifier helpers
> Add unit tests to common_test

- pkg/generate/code/set_resource.go
- pkg/generate/code/set_sdk.go
Issue #, if available: [#922](https://github.com/aws-controllers-k8s/community/issues/922)
* Refactor `setSDKReadMany`:
* use *FindPluralizedIdentifiersInShape* helpers to simplify logic
* Refactor `setResourceForScalar`:
* Remove unused params
* Add `targetVar` param to be the variable's fully-qualified name (i.e. fieldPath+varName r.ko.Spec.CacheClusterID)
> Refactor `setSDKReadMany` and `setResourceForScalar`

- Dockerfile
- Dockerfile.local
- scripts/build-controller-image.sh
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/925
Modify all base and builder images to use ECR public instead of DockerHub
- Requires AWS ECR Public login before any pulls
> Update base images to ECR public

- Makefile
- go.mod
- go.sum
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/894
* aws-controllers-k8s/runtime update from v0.13.0 to v0.13.1
* no interface changes
* ran `go.mod.tidy`
> aws-controllers-k8s/runtime update from v0.13.0 to v0.13.1

- templates/pkg/resource/manager.go.tpl
https://github.com/aws-controllers-k8s/community/issues/931
Solution 2 in the issue linked above. If `rm.Delete` does not return an error, and observed is also nil, return `nil, nil` to the caller instead of the resource passed to the method.
Testing:
`make test`
Manually using sagemaker controller
> return nil if observed is nil from a successful delete

- pkg/model/sdk_helper.go
- pkg/model/sdk_helper_test.go
https://github.com/aws-controllers-k8s/community/issues/932
`getMemberByPath` checks the shape type as it loops through members to ensure lists are handled correctly. Currently I have simply ignored the empty element created by the splitting of the string on the single dot instead of handling the double dot notation explicitly. Open to comments. 
Also added a Unit Test for the same. 
Testing
1. Generated code for ApplicationAutoscaling and ensured CreationTime field now works as expected. Linked changes [in this PR](https://github.com/aws-controllers-k8s/applicationautoscaling-controller/pull/39).
2. Ensured that the SageMaker Controller can be generated using new changes with no diff as expected. 
By submitting this pull request, I confirm …
> Support nested paths in field config specifically list type members

- templates/pkg/resource/resource.go.tpl
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/937
* For implementation of AWSResource.MetaObject, we were returning the complete resource.
* This change only returns 'ObjectMeta' from AWSResource which is the implementation of 'metav1.Object' inside resource struct
* returning only the relevant members helps in metadata comparison correctly with `ackcompare.MetaV1ObjectEqual`
---------------
* Unit tests successful
* Successful local kind e2e test for newly generated dynamodb controller
> Only return MetaObject from AWSResource.MetaObject() call

- Makefile
- go.mod
- go.sum
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/937 https://github.com/aws-controllers-k8s/community/issues/938
* Upgrade to ACK runtime v0.13.2
> Upgrade to ACK runtime v0.13.2

- scripts/install-controller-gen.sh
* Fix installation of controller-gen in prowjobs
* Installing controller-gen in prowjobs fail because $GOPATH/bin directory is not present.
> Fix installation of controller-gen in prowjobs

- pkg/metadata/generation_metadata.go
Recently we introduced a new generate metadata file to all the apiVersions
directory (e.g [EC2 v1alpha1](https://github.com/aws-controllers-k8s/ec2-controller/blob/main/apis/v1alpha1/ack-generate-metadata.yaml)). However after few weeks we realized the 
`last_modification_info` and `ack_generate_info` were too verbose and
often caused merge conflicts since our contributors don't use the same
`OS`/`Arch` for compiling `ack-generate` binary.
This patch removes the last modification timestamp and the OS/Arch from
ack generate information.
- Remove the `OS`/`Arch` from `pkg/metadata.ackGenerateInfo`
- Remove last update timestamp from `pkg/metadata.lastMoficationInfo`
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
> Remove the last modification timestamp and the OS/Arch from `ack-generate-metadata.yaml` file.

- templates/helm/templates/deployment.yaml
- templates/helm/values.yaml.tpl
Description of changes: Added nodSelector label to allow options in case cluster has window and linux nodes. Set default value to linux node.
> Added node selector for helm chart

- scripts/build-controller-image.sh
- scripts/lib/common.sh
Created a new helper method to determine whether the user is currently logged into the ECR public Docker registry. Only if they are not already logged in do we attempt to log in. This will allow the test infrastructure to log in once at the beginning (with a separate role) and ensure that login is stored even after we assume another role.
> Optionally log into ECR public

- templates/pkg/resource/sdk.go.tpl
Adds the `pkg/condition` package from ACK runtime into
`pkg/resource/{RESOURCE}/sdk.go` file. This makes the various common ACK
runtime condition functions like `SetSynced` available to hook code that
may be injected into sdk.go code paths.
> import ACK runtime pkg/condition in sdk.go

- pkg/generate/code/common.go
- pkg/generate/code/set_resource.go
- pkg/generate/config/field.go
- pkg/generate/config/operation.go
- pkg/generate/config/resource.go
- pkg/model/crd.go
- pkg/testdata/models/apis/ecr/0000-00-00/generator-with-field-config.yaml
- pkg/testdata/models/apis/rds/0000-00-00/generator.yaml
- pkg/testdata/models/apis/sagemaker/0000-00-00/generator.yaml
We have had quite a few issues with the logic of `SetResourceIdentifiers` struggling to find the correct identifier field name or matching it to the corresponding spec or status field. The current implementation solves the first of these issues by pointing directly to the identifier member in the input shape, but the logic to link this back to a spec or status field is still flawed. 
Rather than pointing to a member in the input shape and trying to infer the spec or status field, this new implementation directly denotes a field on a resource as the "primary key". The `SetResourceIdentifiers` logic can now directly find the target field and create the corresponding setter. The override logic for ARNs has now been moved to a `is_arn_primary_key` on the …
> Replace `primary_identifier_field_name` with `is_primary_key`

- templates/helm/templates/metrics-service.yaml
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/956
* Previous metric service name for applicationautoscaling-controller was going over 63 characters and failing k8s validation
* Other resources are not at risk because they use template from helpers.tpl which restricts the name to 63 chars
* The issue occurred for this service because we were adding a suffix('-metrics')
* It is important to distinguish metrics service because in future controller can have other kinds of service as well.
* With the proposed solution, the metrics service name looks like `applicationautoscaling-controller-metrics` and is also truncated to never cross 63 chars(max 44 chars from service name + '-controller-metrics')
Tested locally that this works …
> Shorten metric service name

- scripts/lib/common.sh
Just checking the existence of the authorization string in Docker config is not sufficient to determine whether the user is logged into ECR public
This PR will decode the expiration timestamp from the authorization string and compare it to the current UTC timestamp.
> Use docker expiration string from auth config

- scripts/lib/common.sh
* use return statement instead of exit in `is_public_ecr_logged_in` function
* tested locally that `kind-test` passes and builds docker image
*  
> use return statement instead of exit in is_public_ecr_logged_in

- scripts/install-kustomize.sh
fixes aws-controllers-k8s/community#963
The `install-kustomize.sh` was previously in the `community` repo and should live in the `code-generator` repo so that the `olm` scripts can execute properly
> adding back required `install-kustomize.sh` file

- pkg/generate/olm/olm.go
- templates/config/manifests/bases/clusterserviceversion.yaml.tpl
fixes aws-controllers-k8s/community#967
Updating the default `containerImage` and updating the clusterserviceversion template to follow the new image repository formate.
> updating containerImage format in clusterserviceversion

- pkg/generate/code/compare.go
- pkg/generate/code/compare_test.go
- scripts/lib/common.sh
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/951
* Use latest controller-gen release, which unblocks aws-sdk-go upgrade for apigatewayv2 controller
* do not restrict map value type when using `reflect.DeepEqual` method
> Update to controller-gen `v0.7.0`

- Makefile
- go.mod
- go.sum
> Update ACK runtime to v0.14.1

- pkg/generate/olm/olm.go
- templates/config/manifests/bases/clusterserviceversion.yaml.tpl
N/A
This PR aims to keep how `containerImage` tag is generated/built consistent and insync with how `image` tag in the cluster service version is generated. This makes readability of both sections of code/templates/sh's/etc the same and easier in the future if a change in the formate is needed.
> fixing formatting in container image to be consistent with image

- pkg/generate/code/set_resource.go
- pkg/generate/code/set_resource_test.go
- pkg/model/crd.go
- pkg/model/model.go
- pkg/testdata/models/apis/ec2/0000-00-00/generator.yaml
* `model.go` **does not** take into account any `output_wrapper_field_path` overrides when processing Status fields for a CRD
* Refactored `GetOutputShape` api:
* always return an *output* shape
* make `getWrapperOutputShape` private
* updated tests
* Added `GetOutputShape` invocation to `model.go` so that overrides are checked before creating the CRD
Local Testing:
* *generator.yaml*
```
operations:
CreateVpcEndpoint:
output_wrapper_field_path: VpcEndpoint
```
* `make build-controller SERVICE=ec2` 
* **Result:** `VPCEndpointStatus` contains all unpacked fields. Assigning from aws sdk response (`vpc_endpoint/sdk.go`) includes `resp.VpcEndpoint` as prefix
By submitting this pull request, I confirm that my contribution is made under the terms …
> Reference `output_wrapper_field_path` when generating CRD fields as part of the `Create*` request in `model.go`

- cmd/ack-generate/command/apis.go
- cmd/ack-generate/command/controller.go
- cmd/ack-generate/command/crossplane.go
- cmd/ack-generate/command/olm.go
- cmd/ack-generate/command/release.go
- cmd/ack-generate/command/root.go
- pkg/generate/templateset/vars.go
- pkg/model/model.go
- pkg/model/multiversion/manager.go
- pkg/model/sdk_helper.go
- pkg/testutil/schema_helper.go
- scripts/build-controller-release.sh
- scripts/build-controller.sh
Fixes https://github.com/aws-controllers-k8s/community/issues/994
This pull request supports including an optional `--model-name` command line argument for any `ack-generate` generator verb. The generator will use this argument to override the service name when looking up the API files in `aws-sdk-go/models/apis`. 
Currently we reference the `metadata.serviceId` field from the `api-2.json` file as the `ServiceIDClean` variable. `ServiceIDClean` is used in all code generator templates as the import path for `aws-sdk-go` and when referencing the controller name (eg. `{{ .ServiceIDClean}}-controller`). This pull request will redirect `ServiceIDClean` to use the service alias provided when calling `ack-generate`, instead. Therefore, all subsequent ACK repositories …
> Allow separate service ID and alias

- templates/pkg/resource/descriptor.go.tpl
Fixes https://github.com/aws-controllers-k8s/community/issues/998
`GroupVersionResource` is used by dynamic clients to specify the CRD to be CRUD'd.
`GroupKind` is sometimes used in place where the version is not necessarily specified. I chose to export this mainly because it could be used down the line by other dynamic clients.
> Export `GroupVersionResource` and `GroupKind` variables

- templates/config/manifests/bases/clusterserviceversion.yaml.tpl
aws-controllers-k8s/community#1009
ServiceID was removed in a recent commit. One reference was left in clusterserviceversion.yaml.tpl. This PR simply renames that reference to ServiceIDClean to prevent breakage.
> Rename ServiceID reference to ServiceIDClean

- templates/config/controller/deployment.yaml.tpl
- templates/helm/templates/deployment.yaml
ACK runtime v0.15.0 removed support for the `--aws-account-id`
controller flag but our deployment templates were still adding this flag
to the controller entrypoint args, which causes tests to fail with:
```
unknown flag: --aws-account-id
```
Related: #213
See: https://github.com/aws-controllers-k8s/runtime/commit/60801010475969b411d192574c9a47b5acc81bb9
> remove --aws-account-id flag from deployment

- Makefile
- go.mod
- go.sum
Updates the ACK runtime to `v0.15.1`
> Update to ACK runtime `v0.15.1`

- templates/helm/templates/deployment.yaml
- templates/helm/values.yaml.tpl
Removing `account-id` from helm files as they no longer supported in the latest runtime
> remove account-id from helm values and deployment

- pkg/model/op.go
- pkg/model/op_test.go
- pkg/model/sdk_helper.go
- pkg/testdata/models/apis/ec2/0000-00-00/generator.yaml
Issue #, if available: [#999](https://github.com/aws-controllers-k8s/community/issues/999)
* Heuristic to guess resource name will not singularize the resource, if defined in generator resource config. This is to support resources like EC2's DhcpOptions where there is no singular form of the resource.
* unit test
> Add plural names support to `GetOpTypeAndResourceNameFromOpID`

- pkg/names/names.go
- pkg/names/names_test.go
https://github.com/aws-controllers-k8s/ec2-controller/pull/17
- Add `ENA` to initialism list and prevent `"Enable" -> "ENAble" and "Enabling" -> "ENAbling" `
Grep to find other `Ena` words in aws models:
```
$ grep -r 'Ena[a-zA-Z]*' -o .  | sort | uniq | grep -v "Enabl"
./ec2/2016-11-15/api-2.json:EnaSupport
./ec2/2016-11-15/docs-2.json:EnaSupport
./ec2/2016-11-15/examples-1.json:EnaSupport
```
> add ENA to initialism list w/ preventions

- templates/config/controller/user-env.yaml.tpl
Fixes: aws-controllers-k8s/community#1052
Update to make `ack-user-config` and `ack-user-secrets` in the deployment be required for OpenShift. Thus making the operator installation fail false with clearer errors for the cluster admin.
> making ack-user-config and ack-user-secrets required in the deployment template

- templates/crossplane/apis/type_def.go.tpl
Signed-off-by: Aaron Eaton <aaron@upbound.io>
Issue #, if available: https://github.com/crossplane/provider-aws/issues/876
It is possible to have a name collision between a Crossplane Managed Resource and a generated type based on a resource's fields. A good example of this is the SecurityGroup type, which is both a [Managed Resource](https://github.com/crossplane/provider-aws/blob/fd376a39bfebaef2fcc5d1c8fb9177f7e4652bd8/apis/ec2/v1beta1/securitygroup_types.go#L240) and a [generated type](https://github.com/crossplane/provider-aws/blob/76bc036fa0b1cfc5438777cf324922b3634b05e1/apis/ec2/v1alpha1/zz_types.go#L2428).
Whichever type is declared  in the highest apiVersion will become the "storage version" for the given type.
For SecurityGroup, this has no impact, …
> Prevent generated types from colliding with Resources

- cmd/ack-generate/command/crossplane.go
- cmd/ack-generate/command/root.go
- templates/crossplane/README.md
This fixes an issue where the crossplane command would fail to find API
models for resources whose name differed between the model and API in
the SDK. Previous behavior was to continue using the svcAlias instead of
correctly using model_name from the configuration.
The changes here also have the added benefit of making the generateCrossplane function code more similar to other generation functions and utilize more of the common codebase.
N/A
Replace duplicated code in the generateCrossplane function with implementations in common.go and change variables to match the naming scheme used elsewhere.
> Use loadModelWithLatestAPIVersion to load models for crossplane

- templates/config/manifests/bases/clusterserviceversion.yaml.tpl
NA
The community operator repo's tests expects `categories` instead of `category` even if an operator is only going to be listed in OperatorHub under one category.
> changing CSV template to use categories

- pkg/names/names.go
- pkg/names/names_test.go
Generating `EventSourceMapping` resource in the lambda controller
produces a CRD FIeld with a json tag `uUID`. This commit makes sure
that `UUID` names stay intact during code generation.
- Add `UUID` to initialisms
> Add `UUID` to initialism

- pkg/generate/code/set_sdk.go
Originally, this code was added to be able to make `ReadOne` calls when
a resource was not created yet and its ARN is not known, by trying to
build the ARN from the primary identifier field.
Currently `ReadOne` calls uses `requiredFieldsMissingFromReadOneInput`
to know whether a resource was created or not - if a required field is
missing, the `sdkFind` function will return a `ackerr.NotFound`
This also fixes code generation for lambda `CodeSigningConfig` resource
which was panicking because `CodeSIgningConfig` doesn't have a spec
identifier field.
Tested with dynamodb and ECR.
> Remove code setting a resource ARN from its spec primary identifier

- pkg/fieldpath/path.go
- pkg/fieldpath/path_test.go
In attempting to implement the nested field path support for different
source and target field Go types, I realized I needed a support package
that made working with field paths easier, including taking a field path
and finding a ShapeRef within an Output shape that matched the field
path.
This patch introduces a new `pkg/fieldpath` package with a simple `Path`
struct containing a variety of utility methods, as shown in this example
Go code snippet:
```go
import (
"fmt"
awssdkmodel "github.com/aws/aws-sdk-go/private/model/api"
"github.com/aws-controllers-k8s/code-generator/pkg/fieldpath"
"github.com/aws-controllers-k8s/code-generator/pkg/sdk"
)
...
p := fieldpath.FromString("Crawler.Schedule.ScheduleExpression")
// Will print "true"
fmt.Println(p.HasPrefix("Crawler.Schedule"))
// Will …
```
> introduce pkg/fieldpath for processing field paths

- templates/helm/templates/deployment.yaml
- templates/helm/values.yaml.tpl
Closes [#1038](https://github.com/aws-controllers-k8s/community/issues/1038)
This adds affinity, toleration and priorityClassName to the deployment spec as optional parameters.
They default to none, so this will not change any existing functionality.
> Added scheduling parameters to helm template;

- pkg/fieldpath/path.go
- pkg/fieldpath/path_test.go
Adds a few utility methods to `pkg/fieldpath.Path` to make it easier to
inspect associated ShapeRefs at different parts of the path:
* `Path.At(int)` returns the path part at the supplied index.
* `Path.CopyAt(int)` returns a new Path up to the supplied index.
* `Path.ShapeRefAt(*shapeRef, int)` returns a ShapeRef corresponding to
the path part at the supplied index.
* `Path.IterShapeRefs(*shapeRef)` returns a slice of *ShapeRef that can
be used to iterate over the ShapeRefs associated with each of the
Path's parts.
> allow iterating over a fieldpath's ShapeRefs

- templates/crossplane/apis/crd.go.tpl
- templates/crossplane/apis/groupversion_info.go.tpl
Signed-off-by: haarchri <chhaar30@googlemail.com>
Issue https://github.com/aws-controllers-k8s/community/issues/1108 https://github.com/crossplane/provider-aws/issues/1025
changed const Group to CRDGroup to fits generated Group for IAM 
without this PR:
make generate failed with:
`panic: interface conversion: types.Type is nil, not *types.Named`
https://github.com/haarchri/provider-aws/blob/error/group/apis/iam/v1alpha1/zz_groupversion_info.go#L28
https://github.com/haarchri/provider-aws/blob/error/group/apis/iam/v1alpha1/zz_service_linked_role.go#L144
https://github.com/haarchri/provider-aws/blob/error/group/apis/iam/v1alpha1/zz_types.go#L102
fixed issue with this PR:
code-generator works in crossplane for iam: …
> fix(group): group redeclared issue fixed

- pkg/generate/ack/release.go
- templates/helm/values.schema.json
Closes https://github.com/aws-controllers-k8s/community/issues/899
This adds a JSON schema to validate inputs to the helm chart, so that values of an incorrect type, regex or enumeration will fail quickly, rather than after the helm deployment runs.
Please let me know if I've missed any of the enum options.
Also worth noting that regarding the types, this will break functionality for anyone using `"true"`, `"false"`, `1`, `0` as a boolean or `"42"` as an integer, so let me know if you want those added as additional options to those fields.
> Adds helm schema validation

- templates/helm/values.yaml.tpl
Relates https://github.com/aws-controllers-k8s/code-generator/pull/249
Relates https://github.com/aws-controllers-k8s/code-generator/pull/252
This fixes a bug I introduced in a previous PR (sorry!)
This must default to an empty string rather than null or you get:
```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
s3-chart:
- deployment.priorityClassName: Invalid type. Expected: string, given: null
```
> Default priorityClassName to blank string

- pkg/model/field.go
- pkg/model/field_test.go
When inferring the structure of a CRD and its fields, we create a
`pkg/model.Field` struct for each *top-level* field in the CRD's Spec or
Status. The `pkg/model.GetCRDs()` function ends up calling
`pkg/model.CRD:AddSpecField()` and `pkg/model.CRD:AddStatusField()` for
those field definitions that the API inference stage of the generation
pipeline discovers in the aws-sdk-go API model.
Because we were creating `pkg/model.Field` objects for only the
top-level fields in Spec and Status and the `pkg/model.Field` object is
what was tied to a `pkg/generate/config.FieldConfig` object, this meant
that only the top-level field definitions were able to be *configured*
via the generator.yaml file. This is a problem for more complex APIs
like EC2 which have resources with top-level fields that are …
> collect Field structs for members of structures

- templates/pkg/resource/references_read_referenced_resource.go.tpl
* template separate from `references.go.tpl` was using outdated import name
* Used the correct name now
> use correct import name of service-controller repo

- pkg/generate/code/set_sdk.go
- pkg/model/field.go
- pkg/model/field_test.go
- pkg/model/model.go
- pkg/model/model_mq_test.go
- pkg/testdata/models/apis/mq/0000-00-00/generator.yaml
This patch completes earlier work that was done in the `pkg/fieldpath`
package that only uses a single dot notation to refer to a *field* with
type *list* or *map* within a field path.
We previously were using a double dot in field paths in `generator.yaml`
config files to refer to fields of type list or map. This was erroneous,
since referring to the *field* (not the *value* of the field) only
requires a single dot in order for the fieldpath to "locate" a field
within a path.
In this PR, we simplify and DRY up the inference code in
`pkg/model/model.go`'s processing of "nested fields" so that the field
path added for all Field objects uses this single-dot notation only. …
> always use single dot fieldpath notation

- Makefile
- go.mod
- go.sum
* Update ACK runtime to v0.16.1
> ACK runtime update v0.16.0 => v0.16.1

- pkg/model/op.go
- pkg/model/op_test.go
- pkg/testdata/models/apis/ec2/0000-00-00/generator.yaml
Cleans up the `pkg/model:GetOpTypeAndResourceNameFromOpID()` function so
that resources with pluralized singular names can be referred to with
the "cleaned" Camel-cased name in the generator.yaml file. In addition,
corrects an error in said function where the operation returning a
singular pluralized resource -- e.g. DescribeDhcpOptions -- was
incorrectly being returned as OpTypeList instead of OpTypeGet.
> use cleaned name for pluralized resources in cfg

- pkg/model/field.go
- pkg/model/field_test.go
- pkg/model/util_test.go
- pkg/testdata/models/apis/sagemaker/0000-00-00/generator.yaml
A previous commit added functionality to the API/resource inference
process to "unpack" a struct field's member fields into the
`pkg/model.Field.MemberFields` map. However, I had failed to account for
lists or maps of structs. This patch accounts for the list or map of
structs fields, stepping into the list field's element struct type and
adding a Field definition to the containing Field's `MemberFields` map
for each member field in the element struct type. Same for containing
shapes of type "map".
With this patch, we're now able to "access" via field path any nested
field (including its corresponding `FieldConfig` object) which means
that in following patches we can finally resolve the "different Go types
for nested fields" problem we've had in the code generator.
Related issue: …
> unpack struct element/value fields of list/map

- pkg/model/op.go
- pkg/model/op_test.go
Issue #, if available: N/A, [heuristic](https://github.com/aws-controllers-k8s/code-generator/blob/89b0a106fea6268609fd666270518145099646f7/pkg/model/op.go#L110-L118) is returning `ReadOne` operation for `DescribeDhcpOptions` when it is a `ReadMany` call
* returns `OpTypeList` instead of `OpTypeGet` for "singular plural" in `"Describe"` processing
* removes duplicate code
* updates comments on singular-plural description to be clearer and present in all affected areas
> Return `OpTypeList` for singular plurals

- pkg/generate/config/field.go
- pkg/model/field_test.go
- pkg/model/model.go
- pkg/model/sdk_api.go
- pkg/testdata/models/apis/iam/0000-00-00/generator.yaml
Adds functionality for the generator.yaml file to contain a
`FieldConfig.Type` attribute that is the Go type override string for a
field. If the Go type of the field cannot be inferred via the Create
Input/Output shape *or* via the `FieldConfig.From` (SourceFieldConfig)
value, we can look at this new `FieldConfig.Type` value and construct a
`aws-sdk-go/private/model/api:ShapeRef` object manually.
Thus, with this patch, we can do something like this (example from the
iam-controller's generator.yaml file, which is what I tested this patch
on):
```yaml
resources:
Role:
fields:
Policies:
type: "[]*string"
```
> support custom fields of list/scalar/map types

- Makefile
- go.mod
- go.sum
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1133
* ACK runtime update v0.16.1 => v0.16.2
> Update ACK runtime to `v0.16.2`

- pkg/generate/ack/release.go
- templates/helm/templates/NOTES.txt.tpl
Fixes https://github.com/aws-controllers-k8s/community/issues/1135
Adds a cute, descriptive NOTES.txt file for our Helm chart - shown to users when they install the chart.
Example after running `helm install --generate-name s3-chart`:
```
s3-chart has been installed.
This chart deploys "public.ecr.aws/aws-controllers-k8s/s3-controller:v0.0.10".
Check its status by running:
kubectl --namespace default get pods -l "app.kubernetes.io/instance=chart-1642804573"
You are now able to create Amazon Simple Storage Service (S3)
resources in your cluster!
The controller is running in "cluster" mode.
The controller is configured to run in the region: "us-west-2"
Visit https://aws-controllers-k8s.github.io/community/reference/ for an API
reference of all the resources that can …
```
> Add Helm NOTES.txt

- Makefile
- go.mod
- go.sum
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1133
* Upgrade to ACK runtime [v0.16.3](https://github.com/aws-controllers-k8s/runtime/releases/tag/v0.16.3)
* This release fixes the bug where `ACK.ResourceSynced` condition set by `ReadOne/Update` hooks was getting overwritten
> ACK runtime upgrade v0.16.2 => v0.16.3

- pkg/fieldpath/path.go
- pkg/generate/ack/controller.go
- pkg/generate/code/synced.go
- pkg/generate/code/synced_test.go
- pkg/generate/config/resource.go
- pkg/testdata/models/apis/dynamodb/0000-00-00/generator.yaml
- pkg/testdata/models/apis/lambda/0000-00-00/generator.yaml
- templates/pkg/resource/manager.go.tpl
Issue: Generate ACK.ResourceSynced handlers #1064
Currently all the controllers contains custom code that checks whether
a resource is synced or not. This code is mostly used by generic hooks
that sets the `ACK.ResourceSynced` to its correct value. [Generic example
hook](https://github.com/aws-controllers-k8s/rds-controller/blob/main/templates/hooks/db_cluster/sdk_read_many_post_set_output.go.tpl)
This patch adds a new configuration option that will allow controller
maintainers to generate `resource.IsSynced`functions based on some
conditional.
configuration example:
```yaml
resources:
Function:
synced:
when:
- path: Status.State
is: AVAILABLE
- path: Status.State
in:
- AVAILABLE
- ACTIVE
```
generated code example:
```go
// IsSynced returns true if the supplied resource is synced.
func …
```
> Generate resource `IsSynced` functions

- cmd/ack-generate/command/olm.go
- pkg/generate/ack/controller.go
- pkg/generate/ack/release.go
- pkg/generate/olm/olm.go
- scripts/build-controller-release.sh
- scripts/olm-create-bundle.sh
- templates/config/controller/kustomization_def.yaml.tpl
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1076
Adds the `config/controller/kustomization.yaml` file to the release part of the build, so that we can inject the release version and URL to the controller image path. 
Example of new `kustomization.yaml` (for S3):
```yaml
resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
newName: public.ecr.aws/aws-controllers-k8s/s3-controller
newTag: v0.0.11
```
> Add release image to Kustomization

- templates/crossplane/apis/crd.go.tpl
For cases where we do not delete the old version, we need to mark the generated type with storage version.
> Add storageversion kubebuilder marker in Crossplane pipeline

- scripts/build-controller-release.sh
6da05cd introduced a small bug in the RBAC and Service Account names
generation. This patch reverts that specific change.
`SERVICE` variable name is declared in line 116, hence `K8S_RBAC_ROLE_NAME` and
`ACK_GENERATE_SERVICE_ACCOUNT_NAME` should be declared after.
> Fix RBAC Role and Service Account names in `build-controller-release.sh` script.

- Makefile
- go.mod
- go.sum
- pkg/generate/ack/runtime_test.go
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1128
* ACK runtime update to v0.16.4
* ACK runtime update also updates aws-sdk-go dependency to v1.42.0 which supports FIPS endpoints
> dependency updates: ACK runtime v0.16.4 and aws-sdk-go v1.42.0

- cmd/ack-generate/command/olm.go
- cmd/ack-generate/command/release.go
- cmd/ack-generate/command/root.go
- scripts/build-controller-release.sh
- scripts/olm-create-bundle.sh
- templates/config/manifests/bases/clusterserviceversion.yaml.tpl
- Fixes: aws-controllers-k8s/community#1154
- Fixes: aws-controllers-k8s/community#780
- refactoring --image-repository arg so it can be used across cmds
- removing redundant steps in the olm-create-bundle script that is now handled in code/kustomize directly
- referencing new template args in CSV tpl to keep it consistent with the deployment
> refactoring --image-repository arg so it can be used across cmds

- templates/crossplane/apis/crd.go.tpl
- templates/crossplane/pkg/controller.go.tpl
Signed-off-by: haarchri <chhaar30@googlemail.com>
https://github.com/aws-controllers-k8s/community/issues/1150
skip region for `.APIGroup "iam.aws.crossplane.io"` tested locally with https://github.com/crossplane/provider-aws/pull/1118 - it is working now 
> crossplane: feat(iam): if else for iam to skip region

- Makefile
- go.mod
- go.sum
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1161
* ACK runtime from v0.16.4 to v0.16.5
* Release notes: https://github.com/aws-controllers-k8s/runtime/releases/tag/v0.16.5 
> Update ACK runtime from v0.16.4 => v0.16.5

- pkg/generate/code/common.go
- pkg/generate/code/common_test.go
- pkg/generate/code/set_resource.go
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1146
After a recent update to `/pkg/model/field.go`, shapes _may_ contain **additional** fields/members with a "nested" format such as **DHCPOptions.Fields**: `[DHCPConfigurations TagSpecifications.Tags.Value Tags.Value TagSpecifications DHCPConfigurations.Values TagSpecifications.ResourceType TagSpecifications.Tags Tags.Key DHCPOptionsID OwnerID DHCPConfigurations.Key TagSpecifications.Tags.Key DryRun Tags]` The purpose of that update is to allow users to easily fetch nested shapes and their corresponding configurations using the "nested" field name as the key.
However, `SetResourceForStruct` will never have the opportunity to process and/or fetch shapes and configs for these "nested" fields because the …
> Refactor `SetResourceForStruct` to iterate over `targetShape` members

- Makefile
- go.mod
- go.sum
- templates/config/controller/deployment.yaml.tpl
- templates/helm/templates/deployment.yaml
This is the patch that corresponds to changes made to ACK runtime to
rename the `K8S_NAMESPACE` environment variable to
`ACK_SYSTEM_NAMESPACE` to better represent what this variable referred
to.
Related: aws-controllers-k8s/runtime#72
Related: aws-controllers-k8s/community#1178
Issue: aws-controllers-k8s/community#1173
> K8S_NAMESPACE -> ACK_SYSTEM_NAMESPACE

- templates/helm/templates/deployment.yaml
Signed-off-by: Nick Fisher <nxf5025@gmail.com>
Description of changes: The helm chart's values.yaml files have the ability to set `pullPolicy` & `pullSecrets`, but the deployment.yaml does not contain the proper blocks to render the settings. This PR adds both of those.
> Added missing pullSecrets & pullPolicy

- pkg/generate/config/field.go
- pkg/model/field.go
- templates/pkg/resource/references.go.tpl
- templates/pkg/resource/references_read_referenced_resource.go.tpl
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1091
* https://github.com/aws-controllers-k8s/community/pull/1092
* Adds a new `ServiceName` parameter in `ReferencesConfig` to indicate when the referenced resource is from another service controller
* Based on the `ServiceName` parameter imports the API-types from that service controller
* Adds the additional RBAC permissions to allow reading the referenced resource from another service controller
Tested by generating and running apigatewayv2-controller which refers the Subnet and SecurityGroup resource from ec2 controller. Please see the [proposal link](https://github.com/aws-controllers-k8s/community/pull/1092) for generated code.
By submitting this pull request, I confirm that my …
> allow resource references across service controllers

- Makefile
- go.mod
- go.sum
* ACK runtime upgrade v0.17.0 => v0.17.1
* ACK runtime v0.17.1 [release notes](https://github.com/aws-controllers-k8s/runtime/releases/tag/v0.17.1)
> ACK runtime upgrade v0.17.0 => v0.17.1

- templates/pkg/resource/references.go.tpl
* Do not strip the whitespace character **after** third-party imports
*  without the new-line, gofmt was reordering "svcapitypes" import with third-party imports
* validated the fix by generating service controllers locally and the imports inside `references.go` were correct
> Keep local import separation inside references.go.tpl

- Makefile
- go.mod
- go.sum
* ACK runtime upgrade v0.17.1 => v0.17.2
* release [notes](https://github.com/aws-controllers-k8s/runtime/releases/tag/v0.17.2) -> Fixes a bug regarding setting SyncedCondition when there is no delta between desired and latest spec
> ACK runtime upgrade v0.17.1 => v0.17.2

- pkg/generate/code/resource_reference.go
- pkg/generate/code/resource_reference_test.go
- pkg/model/crd.go
- pkg/model/model_apigwv2_test.go
- pkg/testdata/models/apis/apigatewayv2/0000-00-00/generator-with-reference.yaml
- templates/pkg/resource/references.go.tpl
* Use a set of referenced service names for generating import statements inside `references.go.tpl`
* Use sorted fieldnames inside iteration for generating consistent code for `references.go.tpl`. Earlier the generated code was similar but not identical to previous generation. This will reduce cognitive load when reviewing auto-generated PRs
* Added cross service reference manifests for unit testing.
* Manually generated apigatewayv2 controller to test as well.
> BugFix: fixes duplicate import inside references.go

- templates/pkg/resource/references.go.tpl
The current implementation attempts to put all service type imports on the same line. This pull request ensures each import gets a separate line per service and compiles correctly.
> Fix reference import templating

- pkg/generate/code/common.go
- pkg/generate/code/set_sdk_test.go
- pkg/testdata/models/apis/ecr/0000-00-00/generator-renamed-identifier-field.yaml
Currently `FindPluralizedIdentifiersInShape` doesn't take into
consideration CRD field renames. This patch enhances the 
function to be able to lookup field renames and properly find the
matching identifier field.
Fixes https://github.com/aws-controllers-k8s/community/issues/1208
> Consider renaming when trying to find pluralized identifier shapes

- templates/config/controller/deployment.yaml.tpl
Fixes https://github.com/aws-controllers-k8s/community/issues/1224
The environment variables being passed to the deployment in the generated Kustomization are not up-to-date with the [Helm chart](https://github.com/aws-controllers-k8s/code-generator/blob/7052f6808b237f97a2000e4c4f296b9ed2a0d7c0/templates/helm/templates/deployment.yaml#L66-L82). This pull request adds each of the environment variables with the same default values as the ones supplied in `values.yaml`. 
> Add missing Kustomize env vars

- pkg/generate/code/synced.go
- pkg/generate/code/synced_test.go
https://github.com/aws-controllers-k8s/community/issues/1231
Nil check fix for IsSync needed for MemoryDB and
Fixed a compare ignore bug.
> Nil check for IsSync

- scripts/install-operator-sdk.sh
- scripts/olm-create-bundle.sh
N/A
Since there is a change in operator-sdk that isn't compatible with the way ACK `deployment.yaml`'s are built, it's best if we install and use a specific version in the `/bin` folder of the `code-generator`. This way no matter what version of `operator-sdk` a developer has installed, we can control what versions are used for local development and release of this project. 
> adding operator-sdk to the code-generator /bin folder

- pkg/generate/ack/runtime_test.go
- templates/pkg/resource/identifiers.go.tpl
- templates/pkg/resource/sdk.go.tpl
Follow up to https://github.com/aws-controllers-k8s/runtime/pull/79
This patch modifies the code-generator to generate a `Region` function
so that a resource can also satisfy the `Identifiers` interface. This
the patch also extends the `setStatusDefaults` so that it correctly
populates the `status.ResourceMetadata.Region` with the aws region in
which it is created/managed
- Add `Region()` method to resourceIdentifiers template.
- Modifies `setStatusDefaults` to  be able to set the a default region.
- Update `runtime_test.go`
> Generate `Region()` method for `resourceIdentifiers`

- Makefile
- go.mod
- go.sum
* ACK runtime update v0.18.0 => v0.18.1
* ACK runtime v0.18.1 [release notes](https://github.com/aws-controllers-k8s/runtime/compare/v0.18.0...v0.18.1)
> ACK runtime update v0.18.0 => v0.18.1

- Dockerfile
- Dockerfile.local
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1241
Removes the patch version from the Golang base image in our Dockerfiles. This should now use the latest Go 1.17 patch when building images - meaning we can capture the latest security fixes as soon as they become available in the bitnami image.
> Remove patch version from Dockerfile Golang base

- pkg/generate/code/compare.go
- pkg/generate/code/compare_test.go
- pkg/testdata/models/apis/memorydb/0000-00-00/generator.yaml
Updated to trim the prefix "." to calculate the length of the `Spec`.
`cfg.PrefixConfig.SpecField` value is `.Spec` so old code `len(cfg.PrefixConfig.SpecField) + 1` constructed incorrect field path and ignored the config set in `generator.yaml`
Added unit test to validate that below block is not generated.
```
if !ackcompare.SliceStringPEqual(a.ko.Spec.AuthenticationMode.Passwords, b.ko.Spec.AuthenticationMode.Passwords) {
delta.Add("Spec.AuthenticationMode.Passwords", a.ko.Spec.AuthenticationMode.Passwords, b.ko.Spec.AuthenticationMode.Passwords)
}
```
> Fix Spec field length

- templates/pkg/resource/sdk.go.tpl
Set terminal condition if ACK Terminal Error is thrown.
ACK Terminal errors can be used to set terminal conditions
if controller validations fail.
```
if *latestStatus == "create-failed" {
return nil, ackerr.TerminalError.New(errors.New("cluster cannot be updated as its status is not 'available'."))
}
```
> Set Terminal Condition if ACK Terminal Error

- go.mod
- go.sum
Updates the ACK runtime to `v0.18.3`
> Update runtime to `v0.18.3`

- templates/cmd/controller/main.go.tpl
I'd left a TODO in the main.go template for controllers to fill in their
GitVersion, GitCommit and BuildDate information properly. Just now
getting around to this...
Issue: aws-controllers-k8s/community#1171
> add real versions to controller main.go

- pkg/config/operation.go
- pkg/config/resource.go
- pkg/config/version.go
- pkg/model/crd.go
- pkg/model/error.go
- pkg/model/sdk_api.go
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1184 (task 2; migrating access)
* copy methods accessing `ackgenconfig` from model package to config package
* update methods in model package to leverage `ackgenconfig` accessors instead of directly accessing config
* align `ackgenconfig` accessors with config types (i.e. methods accessing `c.Resources` go in `pkg/config/resource.go`)
> Refactor model package to use `Config` accessors

- pkg/config/config.go
- pkg/config/operation.go
- pkg/config/resource.go
- pkg/generate/code/check.go
- pkg/generate/code/common.go
- pkg/generate/code/compare.go
- pkg/generate/code/late_initialize.go
- pkg/generate/code/late_initialize_test.go
- pkg/generate/code/set_resource.go
- pkg/generate/code/set_sdk.go
- pkg/generate/code/synced.go
- pkg/model/crd.go
- pkg/model/error.go
- pkg/model/field.go
- pkg/model/model.go
- pkg/model/multiversion/delta.go
- pkg/model/multiversion/delta_test.go
- pkg/model/sdk_api.go
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1184
* Prepend Getter names with `Get` and remove `error` and `bool` return types
* Re-Name Query (does resource have X, is resource Y) methods to be consistent and styled similarly
* Update comments and fix typos
> Align naming and return types for accessors in config package

- pkg/config/resource.go
- pkg/model/crd.go
- templates/apis/crd.go.tpl
Issue: aws-controllers-k8s/community#1281
Description:
Since all ACK kubernetes resources have a synced condition status,
we need a way to instruct the code generator to generate kubebuilder
marker comments that will append the SYNCED field the `kubectl get`
response.
This patch extends Resource.PrintConfig to allow configuring the
ack-generate to generate such marker comments.
> Add a new generator config to append a `Synced` printer column

- pkg/names/names.go
- pkg/names/names_test.go
Issue #, if available: https://github.com/aws-controllers-k8s/ec2-controller/pull/52
* adds `Ramdisk` to initialisms because the source did not consistently camel case
> update RAM initialism

- templates/config/controller/user-env.yaml.tpl
- Fixes: aws-controllers-k8s/community#1149
Add in support for service specific configmaps and secret so that a cluster admin can configure each service differently, or the same if they so choose.
> add ServicePackageName to ack-user-config and ack-user secrets

- pkg/generate/ack/controller.go
- pkg/generate/code/resource_reference.go
- pkg/generate/code/resource_reference_test.go
- pkg/model/crd.go
- pkg/model/model.go
- pkg/model/model_ec2_test.go
- pkg/testdata/models/apis/ec2/0000-00-00/generator-with-nested-reference.yaml
- templates/pkg/resource/references.go.tpl
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1256
This pull request adds support for references that occur within lists of structs. It updates the generated `references.go` files in each controller to now iterate through the structs to check for the existence of references and again for resolving their individual references. Rather than creating a new slice of structs with resolved references, it instead resolves the references in place - updating the base field value and leaving the reference untouched. 
This pull request has been tested against the APIGatewayv2 and EC2 resource reference tests, as well as manually against the EC2 changes that inspired the original issue.
By submitting this pull request, I confirm that my …
> Add support for references within lists of structs

- pkg/generate/code/set_resource.go
- pkg/generate/code/set_resource_test.go
- pkg/model/crd.go
- pkg/model/model_ec2_test.go
- pkg/testdata/models/apis/ec2/0000-00-00/generator.yaml
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1285
* adds support for list types to `output_wrapper_field_path`
* cleans up logic in `setResourceReadMany`
* updates EC2 unit tests in model and code packages
> Support 'list' type in `output_wrapper_field_path`

- templates/crossplane/README.md
- templates/crossplane/pkg/controller.go.tpl
- templates/crossplane/pkg/conversions.go.tpl
Description of changes: This updates the templates accordingly.
> Crossplane's provider-aws has moved to the crossplane-contrib org

- pkg/generate/ack/controller.go
Issue #, if available: no issue
Create a small helper function so go template can create slice.
It will be used by rds controller soon. 
> Add helper function so go template can create slice

- templates/pkg/resource/manager.go.tpl
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1328
* If the NilFieldPath check is empty, which means that "Tag" field is present at top level, initialize the existing tags inside "AWSResourceManager.ExistingTags" method
* Validated by locally testing using apigatewayv2-controller
> initialize existing tags inside rm.EnsureTags

- go.mod
- go.sum
Update runtime dependency to version `v0.19.1`
> Update runtime to `v0.19.1`

- go.mod
- go.sum
* ACK runtime update to v0.19.2 . [Release Notes](https://github.com/aws-controllers-k8s/runtime/releases/tag/v0.19.2)
> ACK runtime update to v0.19.2

- cmd/ack-generate/command/apis.go
- cmd/ack-generate/command/common.go
- cmd/ack-generate/command/controller.go
- cmd/ack-generate/command/olm.go
- scripts/build-controller-release.sh
Fixes https://github.com/aws-controllers-k8s/community/issues/1361
Code-generator currently compares the subdirectories in the API output directory (`apis/`) to determine the latest K8s version of the CRDs. The information about which API versions should be generated, and their status (`available`, `deprecated`, etc.), already exist in the `metadata.yaml` file. This pull request updates the source of truth for the code-generator to be the `metadata.yaml` file.
> Use metadata as source of truth for latest version

- pkg/generate/ack/controller.go
- templates/pkg/resource/sdk.go.tpl
- templates/pkg/resource/sdk_update.go.tpl
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1374
* Use the correct delta key `Spec.FieldName` when finding changes to immutable field
* If an immutable field is updated, add the Terminal condition in resource and do not continue with update operation until desired state is valid again
> Add Terminal condition when immutable field is updated

- pkg/generate/code/set_sdk.go
- pkg/generate/code/set_sdk_test.go
- templates/pkg/resource/sdk.go.tpl
Fixes https://github.com/aws-controllers-k8s/community/issues/1318
If an ACK resource is evaluated before a secret becomes available, the controller should attempt to retry (with exponential backoff) until the secret exists. This pull request ensures that any error returned by `SecretValueFromReference` is retried by the controller.
Note: I chose not to update the error values in `SecretValueFromReference` because I thought it was more appropriate that the SDK logic chose the requeue action, not the secret fetching method.
> Ensure failed secret dereferencing is recoverable

- templates/config/controller/user-env.yaml.tpl
N/A
To start supporting IRSA in OpenShift clusters, the `user-secret` now needs to be optional.
> making user-secret in user-env optional to support IRSA

- go.mod
- go.sum
* upgrade ACK runtime to v0.19.3
> upgrade ACK runtime to v0.19.3

- templates/helm/templates/deployment.yaml
Removes a suffix trim character from the Helm deployment template. This trim was causing the string to concatenate with the next line and create an error. Removing this ensures it stays as a separate line if the `priorityClassName` is specified.
> Remove faulty suffix trim from Helm deployment

- scripts/build-controller-release.sh
- scripts/install-helm.sh
- scripts/lib/common.sh
Issue #, if available:  https://github.com/aws-controllers-k8s/community/issues/1436
- Add helm version check function
- Add helm installation helper script
- Modify k8s_controller_gen_version_equals function and its comment
> Helm install check

- go.mod
- go.sum
- Upgrade ACK runtime to v0.20.0
> Upgrade ACK runtime to v0.20.0

- scripts/lib/common.sh
Fixes https://github.com/aws-controllers-k8s/community/issues/1438
The current version of `controller-tools` does not support go1.19 (failing with internal atomic type failures). This pull request updates to the latest version, which works as expected.
> Update controller tools to `v0.9.2`

- scripts/build-controller-release.sh
This patch fixes the `tail` command to properly cut the generated
`role.yaml` file and avoid deleteng the `rules` section.
Context:
Recently we bumped `controller-tools` version to `v0.9.2` to support
building controller with go1.19. This change sneakily impacted the
`build-controller-release.sh` script, which caused our prow testing jobs
to fail.
To summarize the bug we can generate the `role.yaml` file using
controller-gen `0.7.0` and `0.9.2` and inspect the differences:
```bash
diff role-controller-gen0.9.2.yaml role-controller-gen0.7.0.yaml
0a1
>
```
We can observe that the new line that used it be generated at the top of
each file is no longer there, due to the fix introduced in 0.8.0 more
precisely in https://github.com/kubernetes-sigs/controller-tools/pull/626
This change combined …
> Fix controller `ClusterRole` file generation

- go.mod
- go.sum
Description of changes: 
* update aws-sdk-go dependency to `v1.44.93` and `go mod tidy`
* related runtime PR: https://github.com/aws-controllers-k8s/runtime/pull/102
> update aws-sdk-go dependency to `v1.44.93`

- go.mod
- go.sum
> Pin ACK runtime to v0.20.1

- templates/helm/templates/_controller-role-kind-patch.yaml.tpl
- templates/helm/values.schema.json
- templates/helm/values.yaml.tpl
Provide option for users to specify Role labels in helm values 
This is useful when using [k8s clusterRole aggregation](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles)
We can use aggregation rule labels to give other applications access to ack resources (Eg: Kubeflow in our case)
> Add helm variable for Role Labels

- pkg/names/names.go
- pkg/names/names_test.go
Description of changes: adds LNI to initialisms with test
> add LNI to initialisms

- pkg/generate/code/compare.go
- pkg/generate/code/compare_test.go
- pkg/testdata/models/apis/iam/0000-00-00/generator-oidc-url.yaml
While generating code for iam-controller OIDC resource, we found a tiny bug causing the code-generator to generate comparison code for a field that was marked as `compare.is_ignored`.
This was found to be the result of the code-generator not properly normalizing field names.
This patch fixes this bug by normalizing the field name using camel case.
This not a good long term fix. Ideally normalization should happen earlier.
Co-authored-by: John Jacobs <jljaco@amazon.com>
> Normalize field names specific to comparison in generator config

- templates/pkg/resource/references.go.tpl
While generating the code for references for the Lambda function, more specifically for the S3 bucket field, we observe that there is use of array keywords with a non-array field e.g len(S3.Bucket) which is incorrect.
After debugging code-generator, we observe that there was an incorrect piece of code (most likely because of copy paste) that considered nested parent field as an array.
This patch fixes this issue by adding the right code for handling nested parent fields.
Unfortunately we cannot add unit tests for this change because this part of the code generation resides inside the template and it's not a part of the pkg/generate/code package.
Fixes https://github.com/aws-controllers-k8s/community/issues/1514 …
> Correct the generated code for nested parent field reference.

- templates/pkg/resource/tags.go.tpl
Issue [#1549](https://github.com/aws-controllers-k8s/community/issues/1549)
- Avoids panic code when customer provides a tag with nil key and nil value.
> Fixes the bug that ToACKTags function does not handle an edge case.

- pkg/model/op.go
- pkg/model/sdk_api.go
There were two bugs in the code generator's construction of the OperationMap during API inference.
The first bug was a non-deterministic behaviour that showed itself when an API had multiple Operations of a single operation type (say, READ_ONE). The code that was responsible for determining which Operation mapped to which operation type for a particular resource was looping over the `aws-sdk-go` `private/model/api:API`'s `Operations` field, which is a map. Depending on the parsing of the underlying api-2.json files, same-typed Operations with different IDs -- e.g. `DescribeStreamSummary` and `DescribeStream` -- were being mapped to a single operation type -- OpTypeGet. Depending on which Operation ID came last, that is the operation that was being mapped, regardless of which one appeared …
> always ensure operation overrides work

- pkg/config/resource.go
- pkg/generate/code/compare.go
- pkg/generate/code/set_sdk.go
- pkg/model/op.go
The code generation for attribute-based APIs (SNS, SQS, etc) had not been kept up to date for 2+ years, meaning that the SNS and SQS controllers could not be regenerated to bring in updated ACK runtimes or aws-sdk-go releases.
This commit gets the attribute-based API code generation back into shape. Most of the changes in here were around the code generator being able to find either ResourceConfig or FieldConfig objects using case-insensitive matching, which turned out to be the main cause for code generator failures when re-generating the SNS controller.
> Fix generation of attribute-based APIs

- pkg/config/config.go
- pkg/config/resource.go
- pkg/model/crd.go
- pkg/model/model.go
Issue #, if available:  [1281](https://github.com/aws-controllers-k8s/community/issues/1281)
We want to have the option to include additional printer columns in the output of `kubectl`.  This change allow the author to specify an arbitrary number of those per Resource, for each specifying the name, type, and JSON path of the field to produce.
> Add a configuration for `additional_columns` at the Resource level

- pkg/generate/code/set_resource.go
- pkg/generate/code/set_resource_test.go
- templates/pkg/resource/sdk_update_set_attributes.go.tpl
Attempting to generate the SNS controller with code-generator <=
v0.21.0 results in various `make test` failures that look like this:
```
[jaypipes@thelio sns-controller]$ make test
go test -v ./...
?   	github.com/aws-controllers-k8s/sns-controller/apis/v1alpha1	[no test files]
pkg/resource/topic/sdk.go:225:8: undefined: err
pkg/resource/platform_application/sdk.go:75:6: resp declared but not used
pkg/resource/platform_application/sdk.go:217:8: undefined: err
pkg/resource/platform_endpoint/sdk.go:75:6: resp declared but not used
pkg/resource/platform_endpoint/sdk.go:113:48: r.ko.Spec.EndpointARN undefined (type "github.com/aws-controllers-k8s/sns-controller/apis/v1alpha1".PlatformEndpointSpec has no field or method EndpointARN)
pkg/resource/platform_endpoint/sdk.go:202:8: undefined: err …
```
> include Spec fields in GetAttributes SetResource

- pkg/model/field.go
- templates/apis/crd.go.tpl
When attempting to generate the SNS controller, I was getting the following failure:
```
[jaypipes@thelio code-generator]$ make build-controller SERVICE=sns
building ack-generate ... ok.
==== building sns-controller ====
Copying common custom resource definitions into sns
Building Kubernetes API objects for sns
Generating deepcopy code for sns
Generating custom resource definitions for sns
Building service controller for sns
Error: template: /home/jaypipes/go/src/github.com/aws-controllers-k8s/code-generator/templates/pkg/resource/delta.go.tpl:34:3: executing "/home/jaypipes/go/src/github.com/aws-controllers-k8s/code-generator/templates/pkg/resource/delta.go.tpl" at <GoCodeCompare .CRD "delta" "a.ko" "b.ko" 1>: error calling GoCodeCompare: runtime error: invalid memory address or nil …
```
> ensure attribute fields have a ShapeRef

- templates/apis/crd.go.tpl
The recent patch ([PR 383](https://github.com/aws-controllers-k8s/code-generator/pull/383)) introduced a regression that caused the
code generator to panic when generating the lambda controller.
This commit addresses the issue by adding a check to ensure that
the shapeRef reference is not nil before accessing the
Documentation field. This prevents the panic from occurring and
allows the code generator to function correctly.
By submitting this pull request, I confirm that my contribution is
made under the terms of the Apache 2.0 license.
> Fix panic in code generator when generating lambda controller

- templates/apis/crd.go.tpl
aws-controllers-k8s/code-generator#383 fixed generation of CRD Go structs for SNS and SQS. Unfortunately, that PR broke Lambda, which has some fields that do not have `ShapeRef` attributes.
aws-controllers-k8s/code-generato#384 fixed Lambda but subsequently re-broke SNS and SQS generation, with `make build-controller SERVICE=sns` producing erroneous whitespace-different CRD Go structs:
```diff
[jaypipes@thelio sns-controller]$ git diff
diff --git a/apis/v1alpha1/ack-generate-metadata.yaml b/apis/v1alpha1/ack-generate-metadata.yaml
index 81fbab0..a894215 100755
--- a/apis/v1alpha1/ack-generate-metadata.yaml
+++ b/apis/v1alpha1/ack-generate-metadata.yaml
@@ -1,9 +1,9 @@
ack_generate_info:
-  build_date: "2022-12-16T20:24:15Z"
-  build_hash: e661ce95afc39b380653ca655503daebf1e1831b
+ …
```
> fix CRD Go struct generation for SNS and Lambda

- go.mod
- go.sum
- templates/helm/templates/deployment.yaml
- templates/helm/values.schema.json
- templates/helm/values.yaml.tpl
Adds a new value in `values.yaml` named `deletionPolicy` to support the controller CLI argument `--deletion-policy`. Supports values of `delete` and `retain`
> Add Helm support for the `--deletion-policy` CLI arg

- templates/pkg/resource/sdk_update_not_implemented.go.tpl
Currently the generated sdk code throws a simple error when `sdkUpdate`
is not implemented. This is only observable in the controller logs and
users are not able to read this information from their resource's
status/conditions.
This patch forces `sdkUpdate` to return a terminal error instead of a
normal error.
Fixes https://github.com/aws-controllers-k8s/community/issues/1521
> Return a terminal error when `sdkUpdate` is not implemented

- templates/config/controller/deployment.yaml.tpl
- templates/config/controller/service.yaml.tpl
- templates/helm/templates/deployment.yaml
- templates/helm/templates/metrics-service.yaml
Issue #, if available: [#1632](https://github.com/aws-controllers-k8s/community/issues/1632)
Improve label selection for service and deployment association with pods. When multiple operators are deployed you may get inconsistent results on the service.
Related [s3-controller/pull/94](https://github.com/aws-controllers-k8s/s3-controller/pull/94)
> add: specific selector for operator

- pkg/config/resource.go
- pkg/model/field.go
A previous commit that used the `github.com/aws-controllers-k8s/pkg/names` package instead of the local `pkg/names` package changed the implementation of the `Field.IsRequired` method slightly by no longer referring to the `names.ModelOriginal` value. This ModelOriginal value was really just a hack from a while ago because we didn't have support for reverse-lookups of renamed fields to original Input/Output struct member names.
This patch adds that reverse lookup and fixes the IsRequired method to properly look up the original struct member name in the Input shape's required list.
> fix required fields that are renamed

- pkg/sdk/repo.go
Issue [#1642](https://github.com/aws-controllers-k8s/community/issues/1642):
add message to remind user to clone aws-go-sdk when timeout due to bad network speed 
```shell
// original
➜  code-generator git:(main) make build-controller SERVICE=ecr
building ack-generate ... ok.
==== building ecr-controller ====
Copying common custom resource definitions into ecr
Building Kubernetes API objects for ecr
Error: canot clone repository: context deadline exceeded
make: *** [build-controller] Error 1
// with new error message
➜  code-generator git:(main) ✗ make build-controller SERVICE=ecr
building ack-generate ... ok.
==== building ecr-controller ====
Copying common custom resource definitions into ecr
Building Kubernetes API objects for ecr
Error: cannot clone repository: …
```
> Add error message for  cloning sdk timeout

- Makefile
- scripts/build-controller-image.sh
- scripts/build-controller-release.sh
- scripts/build-controller.sh
- scripts/construct-metadata.sh
- scripts/install-controller-gen.sh
- scripts/install-helm.sh
- scripts/install-kustomize.sh
- scripts/install-operator-sdk.sh
- scripts/lib/aws.sh
- scripts/lib/common.sh
- scripts/lib/metadata.sh
- scripts/olm-build-bundle-image.sh
- scripts/olm-create-bundle.sh
- scripts/olm-publish-bundle-image.sh
Used the output of the `shellcheck` tool to make style changes to all of the shell scripts within the repository. Added a new `make` target for `lint-shell` which lints all of the scripts and excludes SC1091, which fails because we `source` other scripts using path variables (a known limitation of `shellcheck`).
> Lint all scripts with shellcheck

- scripts/build-controller-image.sh
Since `-i` flag is not supported for the `uname` binary published in the
darwin operating systems, we're switching to `go env GOARCH` to keep the
script working on both linux and darwin OSs.
> Use `go env GOARCH` instead of `uname -i`

- templates/pkg/resource/references.go.tpl
Fixes https://github.com/aws-controllers-k8s/community/issues/1653
Reverts aws-controllers-k8s/code-generator#369
This pull request introduced a change to the way lists of references were accessed, but incorrectly falls back on a conditional that will treat a list of references as a struct. This breaks the `ec2` and `rds` controllers.
> Revert "Correct the generated code for nested parent field reference."

- templates/apis/crd.go.tpl
Closes: https://github.com/aws-controllers-k8s/community/issues/1659
Change CRD type from `boolean` to `string` for `SYNCED` column.
> fix: Make CRD Synced Column type string

- templates/config/controller/deployment.yaml.tpl
- templates/helm/templates/deployment.yaml
- templates/helm/values.schema.json
- templates/helm/values.yaml.tpl
Issue: https://github.com/aws-controllers-k8s/community/issues/1367
Follow-up of https://github.com/aws-controllers-k8s/runtime/pull/106
This patch completes the implementation of support for resource-specific
resync periods and a default drift remediation period made in runtime
repository. The resync period for each reconciler is determined by trying
to retrieve it from the following sources, in this order:
1. A resource-specific period specified in the drift remediation configuration.
2. A resource-specific requeue on success period specified by the resource manager factory.
3. The default drift remediation period specified in the controller configuration.
4. The default resync period defined in the ACK runtime package.
This allows users to customize the drift remediation behavior for …
> Complete support for resource-specific resync periods and default drift remediation period

- go.mod
- go.sum
- pkg/generate/code/set_resource_test.go
- pkg/generate/code/set_sdk_test.go
- pkg/model/model_sqs_test.go
> bring in pkg@v0.0.3

- pkg/generate/code/compare.go
- pkg/generate/code/compare_test.go
- pkg/model/model_s3_test.go
- pkg/testdata/models/apis/lambda/0000-00-00/generator.yaml
- pkg/testdata/models/apis/s3/0000-00-00/generator.yaml
- templates/pkg/resource/delta.go.tpl
Implements https://github.com/aws-controllers-k8s/community/issues/1658
Instead of comparing tag fields using the standard `reflect.DeepEquals`, this PR updates the code-generator to convert the tags to the common `acktags.Tag` type and then compare those as maps. This ensures that changes in ordering do not result in false positive deltas.
Controllers that rely on custom tag delta functions also typically use a function to determine which tags are being added and which are being removed. Using the same trick as this PR, a method can be added to the common runtime to deduce those - resulting in far less duplicated and verbose custom hook code. Those changes are not included in this PR, though. …
> Compare tags using common tag type

- pkg/model/crd.go
This patch addresses the issue of non-deterministic result order in the
`GetImmutableFieldPath` function.
In Go, maps and hashmaps access their elements randomly, which resulted
in non-deterministic return arrays from `GetImmutableFieldPaths`. This
patch leverages `sort.Strings` to ensure deterministic result order,
ensuring deterministic behaviour in generated code.
> Deterministic result order in `GetImmutableFieldPaths`

- templates/config/controller/deployment.yaml.tpl
The runtime expects `--reconcile-resource-resync-seconds` to be an array
of string values. While in deployment.yaml we pass an empty string which
is invalid for `runtime/pkg/config`.
This patch fixes this issue by removing the
`--reconcile-resource-resync-seconds` value
> Fix default value of `--reconcile-resource` flag in deployment.yaml

- templates/config/controller/deployment.yaml.tpl
In the previous commit, we removed the environment variables
not the flags...
> Remove all the `--reconcile-*` flags

- templates/pkg/resource/references.go.tpl
Looks like we missed updating the call to `GoCodeResolveReference` after changing the function signature.
> Correct number of parameters to `GoCodeResolveReference`

- pkg/generate/code/set_sdk.go
The code which builds the input shapes for the GET_ATTRIBUTES and SET_ATTRIBUTES operations for attribute-based APIs was checking for a Name or ID field in order to set the value for ARN fields in the input shapes. However, some resources, like SNS' Subscription resources, do not have a Name or ID field.
This resulted in nil pointer dereferencing and panics when building the controller for SNS Subscriptions.
This patch simply double-checks that the `*string` returned from the `CRD.SpecIdentifierField()` method is not nil before adding in the Go code that constructs an ARN from a Name or ID field.
Related: aws-controllers-k8s/community#1491
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> check for nil Name field in attr APIs

- pkg/config/resource.go
- pkg/generate/code/set_sdk.go
- pkg/generate/code/set_sdk_test.go
- pkg/model/crd.go
- pkg/testdata/models/apis/mq/0000-00-00/generator.yaml
- templates/pkg/resource/sdk_update.go.tpl
Issue: https://github.com/aws-controllers-k8s/community/issues/1598
This patch adds a new generator configuration
`update_operation.omit_unchanged_fields` that instructs the code
generator to generate code that only includes fields in update requests
if their values have actually changed. This is accomplished by using
`delta.DifferentAt` before setting any field in the `newUpdateRequest`
function.
This change will improve the reliability of the generated code by
preventing the controller from trying to update unnecessary fields.
> Add `OmitUnchangedField` config for selective inclusion of changed `CRD` fields in update requests.

- pkg/config/operation.go
- pkg/config/resource.go
- pkg/generate/code/common.go
- pkg/generate/code/set_resource.go
- pkg/generate/code/set_sdk.go
- pkg/model/crd.go
- templates/pkg/resource/sdk.go.tpl
This was a nasty issue to troubleshoot. :( Turns out that for REST+XML-based APIs (such as CloudFront), the aws-sdk-go `private/model/api.Operation` objects have a `Name` field that contains crap like this: "CreateCachePolicy2020_05_31". What this means is that when looking up things like output wrapper field paths by the `Operation.Name` of "CreateCachePolicy" (from the `generator.yaml` file's `operations` map), things were failing because the `private/model/api.API:Operations` map is actually keyed by `Operation.ExportedName`, not `Operation.Name`. `Operation.ExportedName` for REST+XML APIs like CloudFront contain the proper string "CreateCachePolicy" without the date suffix.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> use `Operation.ExportedName` not `Operation.Name`

- templates/pkg/resource/sdk_find_read_one.go.tpl
In the `Pipes` service controller we noticed that the error returned from the API is of type [`RequestFailure`](https://docs.aws.amazon.com/sdk-for-go/api/aws/awserr/#RequestFailure). A workaround is to set `code: ""` in `generator.yaml` or for those not aware of this issue fallback using this new type assertion in `READ_ONE`.
> Add `404: ResourceError` handling in sdkFind

- scripts/olm-create-bundle.sh
- templates/config/crd/kustomization.yaml.tpl
- templates/config/default/kustomization.yaml.tpl
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1690
Migration away from deprecated kustomize feature
> kustomize: use 'resources' instead of deprecated 'bases'

- go.mod
- go.sum
> chore: Update Go deps

- pkg/config/field.go
- pkg/model/field.go
- pkg/model/field_test.go
- pkg/testdata/models/apis/ec2/0000-00-00/generator-with-doc-overrides.yaml
- templates/apis/crd.go.tpl
Adds support for extending the documentation strings for fields and setting docstrings for custom fields.
A new `FieldConfig.Documentation` configuration option is now supported. When present, this string *extends* any documentation provided for the existing field by the doc-2.json files. If no such documentation is provided by the existing field OR if the field is a custom field, the `FieldConfig.Documentation` configuration option is used for the field's docstring in the Go type files.
Example usage for an existing nested field (from a hypothetical ec2 generator.yaml file). The
`LaunchTemplateData.HibernationOptions.Configured` field has a docstring already that contains the following:
```
// If you set this parameter to true, the instance is enabled for hibernation.
//
// Default: …
```
> support field custom documentation strings

- cmd/ack-generate/command/common.go
- pkg/config/config.go
- pkg/generate/templateset/vars.go
- pkg/model/model.go
- pkg/model/sdk_api.go
- templates/crossplane/pkg/controller.go.tpl
- templates/pkg/resource/manager.go.tpl
- templates/pkg/resource/sdk.go.tpl
While developing the ACK pipes-controller, we encountered an issue where
the generated code didn't compile mainly because the code-generator
assumed that the AWS SDK client/interface/import-paths always followed
the same naming conventions. However, we discovered that Pipes was the
exception as they renamed the model, import path, and client
struct/interface.
This patch introduces a new feature that enables users to manually set
the client struct and interface names in the `generator.yaml` file.
This update allows for greater flexibility in the AWS client naming
within pipes-controller and possibly other controllers in the future.
In this patch, we've also introduced a breaking change by renaming
`model_name` to `sdk_names.model`. Mainly to keep all the SDK-related
naming conventions in …
> Allow manual setting of AWS client struct and interface names

- scripts/lib/common.sh
A small quality-of-life improvement for e2e testing workflow when running on a Mac.  Currently, when one isn't logged into `public.ecr.aws`, you get the following when trying to run `make kind-test`:
```
10:36 $ make kind-test                                                                                                                                                                                                                                                    
2023-03-14T10:36:45 [DEBUG] Debug mode enabled                                                                                                                                                                                                                            
... …
```
> QIL improvement to common.sh: check for null return status from ECR call

- cmd/ack-generate/command/crossplane.go
`ack-generate crossplane` fails if there is no `apis/_service_/v1alpha1 directory`. The code includes optGenVersion in the apiPath for goimports which causes an error when the directory doesn't exist.
Removing optGenVersion from the apiPath causes `goimports` to run on all files/directorys under` apis/<service>`
> Remove optGenVersion from api path for goimports

- templates/pkg/resource/descriptor.go.tpl
Replace `GroupKind` with `GroupVersionKind`, in `ResourceDescriptor`, which returns a static GVK using already-defined fields.
> Replace `GroupKind` with `GroupVersionKind` in `ResourceDescriptor`

- pkg/generate/ack/runtime_test.go
Fixes the mocks for the `AWSResourceDescriptor` to use the new `GroupVersionKind` method
**Breaking Changes**: These changes will intentionally break the unit testing, since they are not compatible with runtime `v0.24.x` but are required to upgrade to `v0.25.0`
> Fix mocks for upcoming `AWSResourceDescriptor` changes

- go.mod
- go.sum
Updates the ACK runtime version in `go.mod` to `v0.25.0`
> Pin ACK runtime to `v0.25.0`

- go.mod
- go.sum
Updates the common runtime version to `v0.26.0`
This change introduces updates to the interfaces so we would expect it to break the tests
> Update runtime to `v0.26.0`

- Dockerfile
- Dockerfile.local
Issue https://github.com/aws-controllers-k8s/community/issues/1758
Add some OCI labels to docker images
The labels are documented at https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
Importantly to me, `org.opencontainers.image.source` is used by renovate's changelog support.
> Add OCI labels to docker images

- pkg/generate/code/set_resource.go
- pkg/generate/code/set_resource_test.go
- pkg/testdata/models/apis/sns/0000-00-00/generator.yaml
- pkg/testdata/models/apis/sqs/0000-00-00/generator.yaml
This change basically the SetResource function to continue when the `GetAttribute` operation is present. If the `ReadOne` operation is present then that is preferred.
Issue https://github.com/aws-controllers-k8s/community/issues/1778
> Set Resource when GetAttribute is present

- templates/cmd/controller/main.go.tpl
[fixes https://github.com/aws-controllers-k8s/community/issues/1647]
Completes https://github.com/aws-controllers-k8s/runtime/pull/117
This patch adds a tiny modification to the controllers `main.go` that
passes the resource names to `ackCfg.Validate` method.
Needs a new runtime release.
/hold
> Pass registered resource names to `config.Validate`

- templates/helm/templates/_helpers.tpl
- templates/helm/values.schema.json
- templates/helm/values.yaml.tpl
As the controller runtime supports watching namespaces, we would need to add a support to watch namespaces other than where the controller is deployed. This is a common use case for multi-tenant K8s environments. This PR introduces a `watchNamespace` flag which lets user define the namespaces to be watched by the controller. If left blank, it would take the release namespace.
> Update template to support watch namespace

- templates/config/controller/deployment.yaml.tpl
- templates/helm/templates/deployment.yaml
- templates/helm/values.yaml.tpl
I have recently tried to leveraging k8s built in [Enforce Pod Security Standards with Namespace Labels](https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-namespace-labels/) feature.
When I tried to install one of the controllers I noticed warnings on the [restricted](
https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted) profile.
This I found strange because I checked beforehand and I saw you were already dropping all the capabilities:
https://github.com/aws-controllers-k8s/code-generator/blob/811e30bb8efe2855f79e6e946039247e23c0d03b/templates/helm/templates/deployment.yaml#L112-L118
And hard setting the host env:
https://github.com/aws-controllers-k8s/code-generator/blob/811e30bb8efe2855f79e6e946039247e23c0d03 …
> Add Seccomp profile to deployment

- pkg/config/field.go
- pkg/generate/code/set_resource.go
- pkg/generate/code/set_sdk.go
- pkg/generate/code/set_sdk_test.go
- pkg/model/crd.go
- pkg/testdata/models/apis/iam/0000-00-00/generator-user-newpath.yaml
Issue https://github.com/aws-controllers-k8s/community/issues/1775
- Add new generator config to allow setting an `sdkField` from a specific CR field
> Add new `$field.set[].To` configuration

- pkg/generate/code/set_sdk.go
- pkg/generate/code/set_sdk_test.go
For SQS's `CreateQueue` API, if you pass an empty map to the `CreateQueueInput.SetAttributes()` method, everything succeeds however the service will return the following cryptic error message:
`MalformedInput: End of list found where not expected`
This patch updates the generated code for attribute-based APIs to only call `SetAttributes()` on the input shape when there are attributes to set.
Issue aws-controllers-k8s/community#1695
> only call SetAttributes() when attrMap not empty

- pkg/generate/ack/release.go
- pkg/generate/olm/olm.go
https://github.com/aws-controllers-k8s/community/issues/1715
This pull request updates the release Go code paths and ensures that all `ReleaseVersion` template variables do not contain the `v` prefix.
> Trim possible `v` prefixes in release code

- templates/helm/templates/deployment.yaml
- templates/helm/values.schema.json
- templates/helm/values.yaml.tpl
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/919
Adds additional Helm chart value overrides for deployment environment variables, volumes and volume mounts.
When deploying the `s3-controller` with the following `values.yaml` overrides:
```yaml
deployment:
extraVolumes:
- name: test-volume
secret:
secretName: test-secret
extraVolumeMounts:
- name: test-volume-mount
mountPath: /root/
extraEnvVars: 
- name: SOMEVAR
value: somevalue
- name: PASSWORD
valueFrom:
secretKeyRef:
name: mysecret
key: password
optional: false
```
`helm template` produces the following output:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: release-name-s3-chart
namespace: default
labels:
app.kubernetes.io/name: s3-chart
app.kubernetes.io/instance: …
```
> Add Helm overrides for env vars, volumes and volume mounts

- pkg/model/sdk_api.go
This PR is created to support the code-generation for `FunctionEventInvokeConfig` feature in lambda-controller. [PR#92](https://github.com/aws-controllers-k8s/lambda-controller/pull/92) 
This PR adds functionality to assign whole object to a field, instead of assigning a particular parameter of it. To clarify it further, in the below code, we created a new field `LayerStatuses` which stores the value of `Configuration.Layers` parameter taken from `GetFunction` operation.
```
LayerStatuses:
from:
operation: GetFunction
path: Configuration.Layers
```
In our case we needed to add `FunctionEventInvokeConfig` as an inline property to `Function` resource, for which we needed to assign the whole object returned by `PutFunctionEventInvokeConfig` …
> Adding functionality to assign whole object to a field

- templates/helm/values.yaml.tpl
Fixes https://github.com/aws-controllers-k8s/community/issues/1671
The 0 value of `defaultResyncPeriod` causes the controller to use 10
hours as a `resyncPeriod` .. which is a very confusing.
This patch sets the default value to 36000 (10 hours in seconds) to
match the expected default behaviour.
See https://github.com/aws-controllers-k8s/runtime/blob/main/pkg/runtime/reconciler.go#L48-L51
> Set `defaultResyncPeriod` helm value to 36000

- pkg/generate/ack/hook.go
- templates/pkg/resource/resource.go.tpl
https://github.com/aws-controllers-k8s/community/issues/1871
PolicyName field in Describe and Put APIs for ScalingPolicy has a different name and shape.
| API      |  Field name | Shape |
| ----------- | ----------- | ----------- |
| PutScalingPolicy | PolicyName | String
| DescribeScalingPolicies   | PolicyNames | List of strings
Because of difference in names, the code gen [skips adding it to additional resource identifier for SetIndentifiers](https://github.com/aws-controllers-k8s/code-generator/blob/main/pkg/generate/code/set_resource.go#L1068). Hesitant to use rename because the shape type is different in both APIs (string vs list of string). Adding hooks to unblock …
> add hooks for set identifiers

- templates/crossplane/pkg/controller.go.tpl
This adds a `context.Context` parameter to the `isUpToDate` function in the Crossplane controller template.
Required for https://github.com/crossplane-contrib/provider-aws/issues/1828.
> feat(crossplane): Add context to isUpToDate and return diff

- templates/config/controller/olm-kustomization.yaml.tpl
- templates/config/scorecard/kustomization.yaml
N/A
Updating olm kustomize files using `kustomize edit fix` since some of the methods we were using were marked for deprecation.
> updating olm kustomize files, due to kuztomize deprecations

- templates/config/controller/deployment.yaml.tpl
N/A
Fixing deployment `args` to have boolean values on a single line. This is needed since the presence of the flag itself is a `truthy` statement, and the next line for the `env` is ignored. See [this](https://github.com/aws-controllers-k8s/code-generator/pull/455#discussion_r1282157936) comment on `leader-elect` PR for more info.
> fixing boolean flag in deployment args to be on a single line

- Dockerfile
- Dockerfile.local
Upgrade `eks-distro-build-tooling/eks-distro-minimal-base-nonroot` image to tag `2023-08-24-1692903666.2023`
> Upgrade ACK controllers runtime image

- templates/helm/templates/deployment.yaml
This fixes that setting and use of env variable had different names.
Without this fix leader election is always enabled in controller, but permissions might not be given.
So if leader election isn't enabled in the values you get constant messages like:
`E0911 06:54:26.919325       1 leaderelection.go:330] error retrieving resource lock alb-ingress/ack-acm.services.k8s.aws: leases.coordination.k8s.io "ack-acm.services.k8s.aws" is forbidden: User "system:serviceaccount:alb-ingress:ack-acm-controller" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "alb-ingress"`
> Fix `ENABLE_LEADER_ELECTION` env variable name

- templates/helm/templates/deployment.yaml
Issue: https://github.com/aws-controllers-k8s/community/issues/1893
In this commit, we address the issue of passing boolean flags in a more
solid way. 
We've observed an odd obehaviour when a user attempts to
disabled a feature (e.g `leaderElection/developmentLogging`), which
causes the flag to be enabled instead.
The main root cause of this issue was, using environment vairables with
the `pflag` library, combined with the fact that `spf13/cobra` library
conciders passed boolean flags with no values (no `=<value>`) as `true`
The fix consists of
1. Avoid using environment variables for boolean flags.
2. Updating the helm template to only pass boolean flags when their
respctive helm chat values are present.
By submitting this pull request, I confirm that my contribution is made under the …
> fix: ensure boolean flags are only passed when their corresponding Helm chart value is true

- templates/helm/templates/leader-election-role-binding.yaml.tpl
Issue N/A
Allow leaderElection role to be bound to a custom `ServiceAccount` name, similarily to the main cluster role.
> (fix) enable custom names for service accounts

- go.mod
- go.sum
bump up `github.com/aws-controllers-k8s/pkg` to `v0.0.6`
> bump up `github.com/aws-controllers-k8s/pkg` to `v0.0.6`

- templates/config/controller/deployment.yaml.tpl
- templates/helm/templates/deployment.yaml
- templates/helm/values.yaml.tpl
- Support setting `HostNetwork` and `DnsPolicy` using helm chart values
> Support setting `HostNetwork` and `DnsPolicy` using helm chart values

- templates/helm/templates/deployment.yaml
Issue #, if available: [#1913](https://github.com/aws-controllers-k8s/community/issues/1913)
This PR addresses an issue with the Helm template that generates improper YAML when AWS credentials are provided.
Removed the hyphen `-` in the conditional check for `.Values.aws.credentials.secretName` in the Helm template.
The original template had `{{- if .Values.aws.credentials.secretName -}}`, where the trailing hyphen after the if statement was causing whitespace control issues. This led to improper YAML indentation being generated when `.Values.aws.credentials.secretName` was provided.
The corrected template uses `{{- if .Values.aws.credentials.secretName }}` without the trailing hyphen after the conditional, ensuring that the YAML is generated correctly with the …
> Fix Helm template for AWS credentials secretName

- templates/helm/templates/deployment.yaml
`{{ toYaml .Values.deployment.extraVolumeMounts | nindent 12 }}`
was not aligned with the one created above
`{{- if .Values.aws.credentials.secretName -}}`
removed some indent on the next line when `.Values.aws.credentials.secretName` existed
`{{ end -}}`
let an empty line
Using 
```
aws:
credentials:
secretName: "aws-creds"
secretKey: "credentials-file"
profile: "default"
region: "us-east-1"
deployment:
extraVolumes:
- name: test-volume
secret:
secretName: test-secret
extraVolumeMounts:
- name: test-volume-mount
mountPath: /root/
extraEnvVars: 
- name: SOMEVAR
value: somevalue
- name: PASSWORD
valueFrom:
secretKeyRef:
name: mysecret
key: password
optional: false
```
as a values file I get:
```
apiVersion: apps/v1
kind: Deployment
metadata: …
```
> Fixing compatibility between aws.credentials and deployment.extraVolumes

- pkg/generate/code/compare.go
- pkg/generate/code/compare_test.go
This update enhances the logic for comparing resources in code
generation, especially for collections (maps and arrays) and blob
types. The previous method used nil checks, but they weren't
helpful for these types.
The revised code introduces a new function, `fastCompareTypes`,
to generate Go code that quickly compares two objects of the same
type. For collections, it uses the built-in `len` function to
swiftly spot length differences before diving into detailed checks.
For blobs, the code now employs the `bytes.Equal` function for
straightforward byte array comparisons.
This enhancement aims to make the generated comparison logic more
direct, readable, and efficient, especially when dealing with
collections and blobs in AWS SDK shapes. …
> Enhance resource comparison for collections and blobs

- go.mod
- go.sum
- Pin ACK runtime to `v0.28.0`
- `go mod tidy`
> Pin ACK runtime to `v0.28.0`

- pkg/config/resource.go
- pkg/generate/ack/controller.go
- pkg/generate/code/set_resource.go
- pkg/model/crd.go
- templates/pkg/resource/sdk.go.tpl
- templates/pkg/resource/sdk_find_custom.go.tpl
Issue: aws-controllers-k8s/community#1827
This change allow to implement custom find function. The name of the function could be written in generator.yaml as 'find_operation: <name-of-function>' similar to update_operation. And generated code for sdkFind() would call this custom find function. The find function itself could be written in hooks.go.
> Add `custom find_operation` support

- Dockerfile
- Dockerfile.local
- templates/config/manifests/bases/clusterserviceversion.yaml.tpl
I have tried to start several controllers of aws-controllers-k8s on an ARM EC2 on AWS, but I get the following error.
```
exec ./bin/controller: exec format error
```
To determine the binary format in the Dockerfile, we decided to use TARGETARCH instead of go_arch to facilitate multi-platform build.
> chore: Support multi-arch containers build

- Dockerfile
- Dockerfile.local
Bump `eks-distro-build-tooling/eks-distro-minimal-base-nonroot` to `2023-09-06-1694026927.2`
> Bump build image version

- scripts/build-controller.sh
Default the AWS_SDK_GO_VERSION to last used version for code-generation
Will revert once, we release ARM images for all the controllers.
> Default `AWS_SDK_GO_VERSION` to the last used version for code-generation

- scripts/build-controller-release.sh
> Default `AWS_SDK_GO_VERSION` to the last used version in release script

- pkg/config/field.go
- pkg/model/field.go
- pkg/model/field_test.go
- pkg/testdata/models/apis/eks/0000-00-00/generator-with-gotag.yaml
- templates/apis/crd.go.tpl
This patch introduces a new configuration, `go_tag`, to allow ACK
developers to customize the "Go tags" in the generated structures.
With this configuration users can easily override the default Go tags,
making adjustements like changing the tag name, adding omitempty
directives or even introducing new ones (yaml, gorm, protobuf etc).
This change helps ACK users overcome the challenge imposed by our names
utility package (`aws-controllers-k8s/pkg/names/`) which adds an
underscore suffix to field names that matches Golang keywords. Resulting
in an odd UX when consuming the generated ACK  CRDs (e.g using
`type_: <...>` instead of `type: <...>`)
We purposefully avoided directly modifying the `names` utility package
(trimming the underscores when generating the go tags) as it will break …
> Introducing a generator configuration for GoTag customization

- pkg/config/operation.go
- pkg/model/sdk_api.go
Fixes [#1917](https://github.com/aws-controllers-k8s/community/issues/1917)
**Description:**
The PR adds functionality to use same API for an operation on multiple resources. This allows `ResourceName` to be a list so that same API for an `OperationType` can map to multiple resources. This is required in certain cases where the same API, for same operation is used for multiple resources.
The solution this PR applies is to pass multiple resources for same API.
This supports following cases cases:
1. One API -> One Resource
```
PublishVersion:
operation_type:
- Create
resource_name: 
- Version
```
2. One API -> Multiple Resource
```
DeleteFunction:
operation_type:
- Delete
resource_name:
- Function
- Version
```       …
> Adding functionality to assign one API to multiple resources

- pkg/config/resource.go
- pkg/generate/ack/controller.go
- pkg/model/crd.go
- templates/pkg/resource/sdk.go.tpl
- templates/pkg/resource/sdk_delete_custom.go.tpl
Add custom delete_operation support
> Add ability to set custom `sdkDelete` functions

- pkg/model/attr.go
- pkg/model/model.go
- templates/apis/type_def.go.tpl
Building upon the introduced `GoTag` configuration in https://github.com/aws-controllers-k8s/code-generator/commit/3753ca3f6610172e9e652d6e5e62e0a05f2e639c, this
commit expands the functionality to cover nested fields and attributes.
Now users will be able to set custom Go Tags for nested fields using
JSONPath style directives. e.g:
```yaml
resources:
AccessEntries:
fields:
AccessPolicies.AccessScope.Type:
go_tag: json:"type,omitempty"
```
This patch also refactors `updateTypeDefAttributeWithReference` function
to reuse the code for finding and mutating Attribute objects.
Tested with eks-controller (`AccessPolicies.AccessScope.Type`).
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
> Extend GoTag configuration to nested fields and attributes

- pkg/model/sdk_api.go
> Add support for injecting custom fields of type `bytes`

- templates/helm/templates/role-writer.yaml.tpl
- templates/pkg/resource/sdk.go.tpl
Remove redundant new lines in `sdk.go` and `role-writer.yaml` templates
> Remove redundant new lines in `sdk.go` and `role-writer` templates

- pkg/model/sdk_api.go
While trying to re-generate controllers, we observed this rare error
where the code-generator tries to assign a key/value into a nil map.
Which is an illegal assignement... This should be handled now.
> Safely assign resources to the sdk opType maps

- templates/cmd/controller/main.go.tpl
Previously, we shipped a feature (https://github.com/aws-controllers-k8s/code-generator/commit/d3b23cd5f4a9feae8cb30608e40aa4e18da8bcac) where multi-namespace watch
mode was supported. It turns out that the logic was completely flipped.
We need to assign namespace when the error is NIL and not vice versa. If
the error is NOT NIL, we need to block the controller initiation and
throw an error.
How did we catch this? Nothing special, just reviewing the generated
code and asking who on earth wrote that (me).
This indeed urges us to do proper `CARM`/`multi-namespace`/`cross-region`
testing and write some e2e tests that we can catch these issue very early on ...
When the `code-generator` PRs are drafted.
The current infra doesn't allow us to that, so we'll hack something
around next week. …
> Correctly handle watchNamespace flag parsing errors

- scripts/build-controller-release.sh
Since controller-tools v0.12.0 release - the `controller-gen` binary no
longer injects a null creation timestamp in the CRDs, RBACs and
webhooks. This slightly impacts our code generation process.
This patch fixes a bug that started triming the `rules` directive from
generated RBACs
> Adapt release generator to controller-gen 0.14.0 new format

- templates/helm/templates/cluster-role-binding.yaml.tpl
- templates/helm/templates/cluster-role-controller.yaml.tpl
Issue https://github.com/aws-controllers-k8s/community/issues/2006
This patch default the `watchNamespace` to the release namespace if not
provided.
When a helm chart is installed users can set two parameters to define
the isntallation mode: `installScope`, `watchNamespace`. The latter is
only actionable when `installScope` is set to `namespace`. This patch
defaults the `watchNamespace` to the helm release namespace if the user
doesn't provide any.
> Default watchNamespace to release namespace

- pkg/generate/olm/olm.go
- Relates: aws-controllers-k8s/community#2019
Recently `ControllerName` was introduced to allow controllers to have a custom, more user friendly name. This change caused the `/config/manifest/bases/<SPN>.yaml` to be written to disk incorrectly for controllers that use the new `ControllerName` value. This change switches the `/config/manifest/bases/<CN>.yaml` to be written to disk so that OLM file/package generation can complete successfully and all of the proper values injected into the final `/bundle`.
> update OLM's manifest/bases/csv generation to use `ControllerName`

- scripts/build-controller-release.sh
Updating the logic in the OLM flow to use a the default cache directory.
> updating release script logic for olm flow to use cache director

- go.mod
- go.sum
Bringing `ACM` and `PCA` initialisms
> Pin `github.com/aws-controllers-k8s/pkg` to v0.0.10

- pkg/model/model.go
Prior to this patch, `getAttributeFromPath` searched for paths in spec
fields only. And acted as a no-op when it comes to status fields. This
patch extends the search to status fields as well, allowing us to
configure nested fields in the status as well.
This is gonna be used to configure ECS Cluster `Status.Attachments.Type`
go tags (set `type` instead of `type_`)
> Extend `getAttributeFromPath` search to status fields as well.

- go.mod
- go.sum
Pin ACK runtime to v0.31.0. Mainly addressing two github issues:
- Healthz, liveness and readiness probes https://github.com/aws-controllers-k8s/community/issues/2012
- CARM Race condition and scaling issues https://github.com/aws-controllers-k8s/community/issues/2011
> Pin ACK runtime to `v0.31.0`

- templates/helm/templates/_helpers.tpl.tpl
Issue https://github.com/aws-controllers-k8s/community/issues/2029
Fixed the reference by using `varIncludeTemplate`, so that the controller name is properly prefixed.
Generated ec2 controller code before:
```
{{/* The path the shared credentials file is mounted */}}
{{- define "ack-ec2-controller.aws.credentials.path" -}}
{{- printf "%s/%s" (include "aws.credentials.secret_mount_path" .) .Values.aws.credentials.secretKey -}}
{{- end -}}
```
Which resulted in:
```
Error: template: ec2-chart/templates/deployment.yaml:112:20: executing "ec2-chart/templates/deployment.yaml" at <include "ack-ec2-controller.aws.credentials.path" .>: error calling include: template: ec2-chart/templates/_helpers.tpl:47:20: executing "ack-ec2-controller.aws.credentials.path" at <include …
```
> Fixes Helm reference include reference

- go.mod
- go.sum
Propagating two main patches to all the controllers:
- Properly handle CARM errors and requeues by @a-hilaly in https://github.com/aws-controllers-k8s/runtime/pull/140
- Introduce flags for fine-tuning maximum concurrent reconciles per resource by @a-hilaly in https://github.com/aws-controllers-k8s/runtime/pull/141
> Pin ACK runtime to `v0.32.0`

- templates/helm/templates/deployment.yaml.tpl
This commit addresses the `incompatible types for comparison`
error ncountered during the deployment process (using helm).
The issue was caused by the incorrect comparison of a integer against a
float
This patch fixesd the issues describe above by casting the
`reconcile.defaultResyncPeriod` value to an integerer before performing
the comparison.
> Fix comparison type mismatch in deployment template

- templates/config/controller/deployment.yaml.tpl
- templates/helm/templates/deployment.yaml.tpl
- templates/helm/values.schema.json
- templates/helm/values.yaml.tpl
This patch adds configuration options for reconciler concurrency tuning
(`reconcileDefaultMaxConcurrency` and `reconcileResourceMaxConcurrency`) 
in the Helm chart values, allowing users to customize reconciliation concurrency
for ACK service controllers deployed via Helm charts.
> Expose concurrent reconcile configuration flags in helm chart values

- pkg/fieldpath/path.go
- pkg/fieldpath/path_test.go
This patch updates the `memberShapeRef` function in the `fieldpath`
package to handle case differences between struct member names in the
ACK model and the AWS SDK Model.
Previously, the function assumed that member names in the ACK model and
AWS SDK model were identical. However, this is not always the case, as
some field names may have different casing (e.g `AWSVPCConfiguration` in
the ACK model and `AwsVpcConfiguration` in the AWS SDK model).
To address this issue, the function now leverages `strings.EqualFold` to
compare the member names case isensitively.
> feat(fieldpath): Handle case differences in structure member names

- pkg/config/field.go
- pkg/config/resource.go
- pkg/generate/ack/controller.go
- pkg/generate/code/set_resource.go
- pkg/generate/code/set_sdk.go
- pkg/generate/code/set_sdk_test.go
- pkg/model/crd.go
- pkg/model/field.go
- pkg/testdata/models/apis/lambda/0000-00-00/generator-lambda-ignore-code-sha256.yaml
- pkg/testdata/models/apis/lambda/0000-00-00/generator-with-custom-nested-types.yaml
**Issue** 
This PR is related to fix the issue generating after executing PR #462 
**Summary**
To disregard fields marked with `set: ignore` for nested fields. This PR also enhances the functionality of `set:ignore` to support the exclusion of fields from `set_sdk`.
**Description**
The PR  fixes the issue coming after a new custom field is created and has `set.ignore` set to `true` for it. Even after setting the field to ignore, the field is getting used to set the SDK fields. In this case particularly, the new field was defined as shown below:
```
Code.S3SHA256:
type: string
set:  
- method: Create
ignore: true
```
And the issue it is causing is under `sdk.go/newCreateRequestPayload` function, where it is being set, as shown below:
```
if r.ko.Spec.Code.S3SHA256 != nil { …
```
> Functionality to make `ignore` work

- Dockerfile
Dodging CVE scanners before it's late :)
> Update base image to `eks-distro-minimal-base-nonroot:2024-04-01-1711929684.2`

- go.mod
- go.sum
> Pin ACK runtime to v0.37.0

- pkg/generate/code/set_resource.go
- pkg/generate/code/set_sdk.go
- fix logic that allows ignoring SDK setters (i.e. `sdkCreate` and `sdkUpdate`) for nested fields. The field path map is currently queried using a wrong key i.e. the field name instead of field path.
- introduce logic that allows ignoring Resource setters (i.e. `sdkFind`). 
> Fix logic that allows ignoring Resource and SDK setters

- go.mod
- go.sum
- templates/helm/values.yaml.tpl
- Add CARMv2 as a featureGate, disabled by default
- Pin runtime to v0.37.1
> Pin runtime to `v0.37.1`

- pkg/config/config.go
- pkg/generate/code/set_sdk.go
- pkg/model/model.go
Issue #, if available: prerequisite for WAFv2 [RuleGroup](https://github.com/aws-controllers-k8s/wafv2-controller/pull/6) and [WebACL](https://github.com/aws-controllers-k8s/wafv2-controller/pull/7) CRDs
Some WAFv2 API fields have empty json specs `{}`, e.g. https://docs.aws.amazon.com/waf/latest/APIReference/API_AllQueryArguments.html
For these type of fields, codegen currently errors out because it infers their gotypes as e.g. 
`AllQueryArguments *AllQueryArguments`
but does not generate a `type AllQueryArguments struct` since the struct itself is empty, and not picked up by `newFieldRecurse` function.
The solution proposed in this PR is to allow users to define `marker-shapes`, which instruct codegen to overwrite the type of these empty structs as `[]byte`, both …
> Add support for empty shapes, used as booleans in SDK

- templates/helm/templates/deployment.yaml.tpl
https://github.com/aws-controllers-k8s/community/issues/2166
Configure the generated helm chart to set a readOnlyRootFilesystem on pods for ACK controllers to improve the security posture.
> use readOnlyRootFilesystem

- scripts/lib/common.sh
Looks like controller builds will start failing once we move to controller-runtime v0.19.0
Just trying to stay ahead of the dependencies here
> Force controller-gen `v0.16.2` for all controller

- templates/helm/values.yaml.tpl
> Expose `ReadOnlyResources` featuregate in ACK helm chart

- pkg/generate/code/set_sdk.go
Add a conditional check in `SetSDKSetAttributes` to only call `SetAttributes`
when the attribute map is not empty. This prevents API validation errors
that occur when setting an empty attribute map.
> Add conditional check before setting attributes in `SetSDKSetAttributes`

- Dockerfile
- Dockerfile.local
- scripts/build-controller-image.sh
This change allows us to pass the base image version 
as an argument allowing us to pass the latest one after each release
> Make controller base_image version an argument

- templates/pkg/resource/descriptor.go.tpl
Issue #, if available: closes [#2201]( https://github.com/aws-controllers-k8s/community/issues/2201)
Description of changes: Rename finalizerString to FinalizerString to export the constant.
> feat: rename finalizerString to FinalizerString

- templates/helm/templates/caches-role-binding.yaml.tpl
Relates to https://github.com/aws-controllers-k8s/kms-controller/pull/83
Description of changes: This change ensures that the required `ClusterRoleBinding` and `RoleBinding` objects apply to a `ServiceAccount` with a custom name.
Error seen with custom service account name:
```
pkg/mod/k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:kms-controller:kms-controller" cannot list resource "configmaps" in API group "" in the namespace "kms-controller"
```
> fix(helm): Ensure non-default service account name works with namespaces-cache and configmaps-cache role bindings

- go.mod
- go.sum
- pkg/generate/ack/controller.go
- pkg/generate/code/set_resource.go
- pkg/generate/code/set_resource_test.go
- templates/pkg/resource/resource.go.tpl
These changes introduce a new generated function in all controllers 
that attempts to populate the resource spec/status with fields defined 
by the user. 
This change will require for developers to add hooks for this function to 
all controllers that already have a `SetResourceIdentifiers` hook.
> feature: Generate Code for resource adoption by annotation

- templates/pkg/resource/resource.go.tpl
This function is similar to the `SetIdentifiers` function. 
If any controller has a hook for `SetIdentifiers`, we need 
a similar one for `PopulateResourceFromAnnotation`
Hooks:
* `pre_populate_resource_from_annotation`
* `post_populate_resource_from_annotation`
> Add hook code to `PopulareResourceFromAnnotation`

- go.mod
- go.sum
> Pin `ACK` runtime to `0.40.0`

- templates/pkg/resource/manager.go.tpl
- templates/pkg/resource/tags.go.tpl
Issue [#2248](https://github.com/aws-controllers-k8s/community/issues/2248)
By generating these two functions, we ensure that AWS tags will not 
be present in resource Spec during adoption/regular reconciliations.
FilterSystemTags will be called right after the ReadOne operation during
adoption, and it will ensure we don't patch AWS (aws:cloudformation..)
or Controller tags (services.aws.k8s/...) into the resource.
MirrowAWSTags instead, is called during the regular reconciliation loop,
after each ReadOne operation. It ensures that if the resource in AWS has
AWS tags, they need to be reflected in the desired Spec. This will ensure
that those tags will not be detected in the Delta and trigger an update. 
Since the controller only patches the difference between the …
> Generate FilterSystemTags and mirrorAWSTags in controllers

- go.mod
- go.sum
- pkg/generate/ack/runtime_test.go
- templates/pkg/resource/manager.go.tpl
- templates/pkg/resource/tags.go.tpl
> Pin ACK runtime to v0.43.0

- pkg/config/field.go
- pkg/model/crd.go
- pkg/model/field.go
- templates/apis/crd.go.tpl
- templates/crossplane/apis/crd.go.tpl
- templates/pkg/resource/sdk.go.tpl
- templates/pkg/resource/sdk_update.go.tpl
Issue #2202
Updates the ACK code generation process to enforce immutability using CEL validation rules instead of runtime comparisons. By adding `+kubebuilder:validation:XValidation` annotations to fields marked `is_immutable: true`, Kubernetes `1.25+` now blocks changes at admission time, eliminating the need for separate runtime checks or conditions.
1. More immediate feedback: Users get a direct error when attempting to mutate an immutable field.
2. Less runtime complexity: We no longer need to detect or conditionally reject these changes in the controller code.
3. Cleaner codegen: The old `HasImmutableFieldChanges()` and similar logic can be removed.
Clusters must be on Kubernetes 1.25+, which supports CEL. …
> Switch ACK to CEL-Based Immutability and Remove Runtime Checks

- templates/apis/crd.go.tpl
This PR fixes a templating issue where multi-line documentation strings were being truncated due to template whitespace control markers. 
> fix documentation templating bug

- pkg/model/model.go
- pkg/model/model_route53_test.go
- pkg/testdata/codegen/sdk-codegen/aws-models/route53.json
- pkg/testdata/models/apis/route53/0000-00-00/generator.yaml
So currently, when you define a `from` `operation` `path`
in generator.yaml fieldConfig, the code-generator checks for
the read_only configuration to decide whether to get the field
from the input shape or the output shape.
The change introduced here tries to retrieve spec fields from input
shapes first, if not found it checks output shape.
If read_only is configured to true, it does so in reverse order
(checks output shape first, if not found, checks input shape)
> Expand the search space for shapes in `from.operation`

- pkg/generate/ack/controller.go
- pkg/generate/code/compare.go
- pkg/generate/code/compare_test.go
- pkg/generate/code/tags.go
- pkg/generate/code/tags_test.go
- templates/pkg/resource/manager.go.tpl
- templates/pkg/resource/tags.go.tpl
This change also ensures these functions are generated using 
go code instead of templating. This keeps the code cleaner and testable.
> Replace To/FromACKTags with to/fromACKTagsWithKeyOrder

- templates/cmd/controller/main.go.tpl
- templates/helm/templates/deployment.yaml.tpl
- templates/helm/values.schema.json
- templates/helm/values.yaml.tpl
Adds the configured watch selectors to the controller managers cache options, allowing
filtered resource watching based on labels.
> feat: Add watch selector support to controller manager

- pkg/generate/code/set_resource.go
- pkg/generate/code/set_resource_test.go
The error message returned from PopulateResourceFromAnnotation was 
not descriptive enough, as it did not include the name of the required field 
that was missing.
This change is including the field name in the error message.
> chore: Enhance PopulateResourceFromAnnotation error message

- pkg/generate/ack/release.go
- templates/helm/templates/deployment.yaml.tpl
- templates/helm/values.schema.json
- templates/helm/values.yaml.tpl
https://github.com/aws-controllers-k8s/runtime/pull/176
This PR adds template changes to support the reconcile-resources flag which was recently added to the ACK runtime. This flag allows users to specify which resource kinds should be reconciled by a controller, providing more granular control over controller behavior.
When the flag is set, only the specified resource kinds will be reconciled by the controller. If unspecified, all resources will be reconciled (default behavior).
> add support for `reconcile-resources` flag

- pkg/api/legacy_io_suffix.go
- pkg/generate/code/set_resource.go
- pkg/generate/code/set_sdk.go
Currently, generating Maps of Enums was error prone. Instead of generating them.
With these changes, we ensure map[string]Enum are generated properly.
Sample:
```golang
f0valf28f0f0 := map[string]svcsdktypes.GlueRecordType{}
for f0valf28f0f0key, f0valf28f0f0valiter := range f0valiter.JDBCConnectorSource.AdditionalOptions.DataTypeMapping {
var f0valf28f0f0val string
f0valf28f0f0val = string(*f0valf28f0f0valiter)
f0valf28f0f0[f0valf28f0f0key] = svcsdktypes.GlueRecordType(f0valf28f0f0val)
}
```
> fix: ensure maps of enums are generated properly

- cmd/ack-generate/README.md
Issue #, if available: None
Description of changes: Update the outdated relative link to the build script.
> docs: modify scripts path

- pkg/apiv2/remove_defaults.go
- Update BadDefaultsAssignment map to include AmazonBedrockAgentBuildTimeLambda.StorageDays to fix missing pointer operations
> Add BedRock Agent.MemoryConfiguration.StorageDays to BadDefaultsAssignment

- pkg/generate/code/set_sdk.go
- pkg/generate/code/set_sdk_whitebox_test.go
- Update `set_sdk.go setSDKForScalar()` to allow zero and negative values for float32 in bounds check
> Allow zero and negative values for generated float32 bounds check

- pkg/api/shape.go
- pkg/apiv2/converter.go
- pkg/model/field.go
- pkg/model/field_test.go
Issue #, if available: [930](https://github.com/aws-controllers-k8s/community/issues/930)
- Read smithy.api#pattern from aws-sdk-go-v2 JSON models
- Add Regex pattern to documentation string if exists
- Add test to verify pattern string is added when present
> Add Regex Pattern to documentation

- templates/config/controller/service.yaml.tpl
Issue #, if available: [2506](https://github.com/aws-controllers-k8s/community/issues/2506)
- Use ClusterIP as default Service type for metrics for non-Helm installations
> Use ClusterIP as default Service type

- go.mod
- go.sum
- Update runtime version to v0.48.0
> Pin ACK runtime to v0.48.0

- pkg/generate/code/set_sdk_test.go
- pkg/model/model_lambda_test.go
- pkg/model/types.go
- pkg/testdata/models/apis/lambda/0000-00-00/generator-environment-vars-secret.yaml
- Add Test case for mapping string to secrets references
- Update CleanGoType to update value type of map to SecretKeyReference if is_secret set.
- Add tests validating SetSDK() for map of secrets references
> Support Map of SecretKeyReferences

- pkg/sdk/repo.go
The timeout being 30 seconds was causing a timeout error. 
Moving forward we may want to make certain changes to make the fetch faster
> chore: increase `git fetch` default timeout to 180s

- templates/helm/templates/deployment.yaml.tpl
The AWS ACK Helm chart generates `"volumes": null` when no static secret `.Values.aws.credentials.secretName` or no extra volume `.Values.deployment.extraVolumes` was set. This can cause issues during the deployment, particularly with admission controllers such as policy engines. An example issue can be found here https://github.com/kyverno/policies/issues/1310 by Kyverno. 
This PR solves such problems without using a workaround, like deploying an unused emptyDir.
> fix(helm): avoid null volumes in deployment

- scripts/build-controller-image.sh
Issue [#2568](https://github.com/aws-controllers-k8s/community/issues/2568)
- Fix incorrect usage of non-existent go_arch build arg
- Add `--platform` flag based on value of GOARCH
> Respect GOARCH value in build-controller-image.sh

- templates/helm/templates/caches-role-binding.yaml.tpl
**Issue:**
```
Failed to watch *v1.Namespace: failed to list *v1.Namespace: namespaces is forbidden: User \"system:serviceaccount:ack:ack-iam\" cannot list resource \"namespaces\" in API group \"\" at the cluster scope: RBAC: clusterrole.rbac.authorization.k8s.io \"ack-iam-iam-chart-namespace-caches\" not found"
```
ClusterRoleBinding can not mount ClusterRole `ack-iam-iam-chart-namespace-caches` because it doesnt exist.
Fix the naming of ClusterRoleBinding and ClusterRole attached to it.
**Fixes issue from PR:** 
https://github.com/aws-controllers-k8s/code-generator/pull/593
> fix: Wrong ClusterRole name in caches ClusterRoleBinding

- templates/helm/templates/deployment.yaml.tpl
Issue [#2583](https://github.com/aws-controllers-k8s/community/issues/2583) 
This PR addresses an issue encountered when rendering a Helm chart that includes additional volumes, such as an emptyDir. The change ensures with `-` that leading whitespace is trimmed and using `nindent` instead of `indent` prevents unwanted blank lines. The issue originates from the following pull request https://github.com/aws-controllers-k8s/code-generator/pull/608.
To manually validate the fix of this PR in a chart based on the code-generator follow the steps below:
```
$ helm pull oci://public.ecr.aws/aws-controllers-k8s/acm-chart --version 1.0.14 && tar -xzf acm-chart-1.0.14.tgz
$ sed -i '208s|.*|        {{- toYaml .Values.deployment.extraVolumes \| nindent 8 }}|' …
```
> fix(helm): indent of extra volumes

- pkg/generate/code/set_resource.go
- pkg/generate/code/set_resource_test.go
fixes [#2557](https://github.com/aws-controllers-k8s/community/issues/2557)
During resource Adoption, the ACK controllers only returned an error 
when there was a missing PrimaryKey. If a Resource requires more than 1 
field to describe a Resource (eg. Lambda alias requires Name and
FunctionName), the controller only verifies the Primary identifier (ARN, 
ID, Name) and nothing else.
With this change, we look into the SDK model to retrieve the required 
fields and return an error if all are not defined during 
`PopulateResourceFromAnnotation`
> feat: return error on missing required fields during adoption

- templates/helm/templates/deployment.yaml.tpl
- templates/helm/values.schema.json
- templates/helm/values.yaml.tpl
fixes https://github.com/aws-controllers-k8s/community/issues/2625
- reads enableCARM value from values.json
- supplies arg to controller to disable CARM when set to false
> feat: reads enableCARM value and supplies to controller

- scripts/lib/common.sh
- Change CONTROLLER_TOOLS_VERSION environment variable default value to `v0.19.0`
> Upgrade default controller-gen version to v0.19.0

- pkg/model/crd.go
Fields marked with `is_attribute: true` were intermittently losing their documentation comments during code generation. These fields get processed twice:
1. From AWS SDK model (with documentation)
2. From attribute unpacking (with `nil` ShapeRef, losing documentation)
The issue was **non-deterministic** - sometimes documentation was preserved, sometimes it was lost, even with identical configuration.
**Cause**
The execution order depended on **Go's randomized map iteration** in `pkg/model/model.go`:
```go
for memberName, memberShapeRef := range inputShape.MemberRefs {
```
Since both field creation paths store to the same map location (`r.Fields[fPath]`), whichever runs **last wins**:
- **Lucky order**: Attribute unpacking → AWS SDK processing = Documentation …
> Fix documentation loss for attribute fields

- pkg/generate/code/set_resource_test.go
- pkg/generate/code/set_sdk.go
- pkg/generate/code/set_sdk_test.go
- pkg/testdata/codegen/sdk-codegen/aws-models/firehose.json
- pkg/testdata/models/apis/firehose/0000-00-00/generator-set-for-nested-field.yaml
Add support for applying Set config's `-to` to child fields of Struct field.
- Check for SetConfigs for child fields in SetSDKForStruct
- Add testdata for firehose service
- Add unit test to verify nested set behavior.
- Cleanup leftover print statement
> Add support for nested fields when using Set config
